### ISSUE TITLE
New docs are wrong

### ISSUE THREAD

**Issue by brendencallahan** [rebelot/kanagawa.nvim#102]
I'm not sure why the breaking changes were made but it seems the docs didn't get fully updated. They suggest that you can just set config.theme = "wave" but that gives you an error that config.theme must be a table.

![image](https://user-images.githubusercontent.com/47364240/222916019-eeb398bd-73ad-4cd3-ae16-bb03f6fadc6f.png)

**Comment by rebelot** [comment]
Sorry, the docs are right, the error message is wrong. Will fix asapOn 4 Mar 2023, at 16:58, Brenden Callahan ***@***.***> wrote:﻿
Closed #102 as completed.

**Comment by brendencallahan** [comment]
Yeah, it was my mistake which I why I closed it right away. Better error messages are always good though, thanks.
