### ISSUE TITLE
Nvim-tree background broken

### ISSUE THREAD

**Issue by brendencallahan** [rebelot/kanagawa.nvim#103]
I'm not sure why the breaking changes would affect this but now I have a darker background for nvim-tree. The background should be one color but instead nvim-tree is darker. 

![image](https://user-images.githubusercontent.com/47364240/222916458-af610849-c77f-4b81-85bc-1d9698c7ecbd.png)

**Comment by fbearoff** [comment]
This is fixed for me by https://github.com/rebelot/kanagawa.nvim/issues/104#issuecomment-1454862476

**Comment by brendencallahan** [comment]
I might try that if this doesn't get resolved. For now I've just rolled back to a previous commit that's stable. Even if that fixes it I'm going to leave this issue open for now because if I set 'transparent = true' and 'dimInactive = false' I would not expect to have to manually set a bg_gutter.

**Comment by rebelot** [comment]
I think the issue is with NvimTreeNormal and NvimNormalNC isn't it?

**Comment by brendencallahan** [comment]
Possibly? I'm not manually setting either of those though so it should respect the transparency setting. Let me know if you need help reproducing.

**Comment by rebelot** [comment]
> Possibly? I'm not manually setting either of those though so it should respect the transparency setting. Let me know if you need help reproducing. 

I mean, the two hlgroups I mentioned are the ones responsible for NvimTree background. You don't have to set them. For the time being, you can override them and set their background to "none"
