### ISSUE TITLE
Line Numbers background broken

### ISSUE THREAD

**Issue by ElcomJ** [rebelot/kanagawa.nvim#104]
After the last `commit`, my `CursorLineNr `background configuration don't work, before it was transparent, now it's ignored as shown in the image below:

Settings to set transparent:

![Screenshot from 2023-03-04 16-32-13](https://user-images.githubusercontent.com/37147897/222925328-486e4fe2-5fac-4272-855d-dbbeaa3d7741.png)

Before the last commit:

![Screenshot from 2023-03-04 16-34-24](https://user-images.githubusercontent.com/37147897/222925393-d46d4f13-1454-420c-8ca1-808ab92e759c.png)

After the last commit:

![Screenshot from 2023-03-04 16-32-26](https://user-images.githubusercontent.com/37147897/222925401-11097c97-1e09-4525-abd3-da35ed38a9be.png)

**Comment by catgoose** [comment]
I'm glad lazy.nvim allows me to specify commits.  I may be `commit = "de7fb5f",` forever.

**Comment by rebelot** [comment]
To remove gutter background, use 

```lua
require'kanagawa'.setup{
  colors = {
    theme = { all = { ui = { bg_gutter = 'none' }  }}
  }
}
```

**Comment by ElcomJ** [comment]
@rebelot I tried your answer and the error continues, it keeps ignoring my configuration.

Ps: I already updated the plugin to the new commit.

**Comment by ElcomJ** [comment]
No need to worry anymore, I've gone back to nightfox.

Thanks for your attention and congratulations for the great work, have a great day :)

**Comment by rebelot** [comment]
> No need to worry anymore, I've gone back to nightfox.
> 
> Thanks for your attention and congratulations for the great work, have a great day :)

I am sorry you could not find a satisfying solution. You should make sure your custom highlights are source _after_ a colorscheme is loaded. Best practices would advise to wrap your overrides into a `ColorScheme` autocmd.

Also remember that for any changes to take place, whenever you edit your config, you should run `KanagawaCompile` command. This is probably why you couldn't see the changes.

**Comment by kohane27** [comment]
Before:

![2023-03-07-05-31-00](https://user-images.githubusercontent.com/57322459/223235498-df1cedc4-9518-4ea3-862c-f1b88fb123b7.png)

After adding the line as suggested above:

![2023-03-07-05-31-11](https://user-images.githubusercontent.com/57322459/223235508-0fba8c5e-6042-4010-a9e2-b7ccb1d02b33.png)

I think `bg_gutter`'s default value was changed, hence the visual change?

I think there are breaking changes recently? I used to have the `variablebuiltinStyle` field but now it's gone.

I understand that you're maintaining it on your free time and for free. I really appreciate this very nice and warm theme and I wouldn't complain in any other way. But, just as a suggestion, is it possible that you could notify existing users that there are breaking changes in the README? Not necessarily maintaining a list of breaking changes (I understand it increases the workload) but a warm reminder would be nice.

Thank you @rebelot again for creating and maintaining kanagawa. This is the best theme for me and daily driving it has made my life better.

**Comment by rebelot** [comment]
@kohane27 https://github.com/rebelot/kanagawa.nvim/issues/79

**Comment by maconsuckow** [comment]
I can't seem to get these fixes to work. I have the below config. And none of the options I have commented out have any affect. After any of the changes, I quit nvim, reopen and run `:KanagawaCompile`. I don't see any immediate effects, so I quit nvim and reopen and I still don't see any changes. 

Have anyone else gotten this to work?

```
return {
	"rebelot/kanagawa.nvim",
	enabled = true,
	compile = true,
	lazy = false,
	build = "KanagawaCompile",
	opts = {
		transparent = true,
		commentStyle = { italic = true },
		theme = "dragon",
		-- colors = {
		-- 	all = {
		-- 		ui = {
		-- 			bg_gutter = "none",
		-- 		},
		-- 	},
		-- },
		overrides = function(colors)
			local theme = colors.theme

			-- colors = {
			-- 	all = {
			-- 		ui = {
			-- 			bg_gutter = "none",
			-- 		},
			-- 	},
			-- }

			return {
				NormalFloat = { bg = "none" },
				FloatBorder = { bg = "none" },
				FloatTitle = { bg = "none" },
				CursorLineNr = { fg = "none" },

				-- Save an hlgroup with dark background and dimmed foreground
				-- so that you can use it where your still want darker windows.
				-- E.g.: autocmd TermOpen * setlocal winhighlight=Normal:NormalDark
				NormalDark = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },

				-- Popular plugins that open floats will link to NormalFloat by default;
				-- set their background accordingly if you wish to keep them dark and borderless
				LazyNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },
				MasonNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },

				Pmenu = { fg = theme.ui.shade0, bg = theme.ui.bg_p1 },
				PmenuSel = { fg = "NONE", bg = theme.ui.bg_p2 },
				PmenuSbar = { bg = theme.ui.bg_m1 },
				PmenuThumb = { bg = theme.ui.bg_p2 },
			}
		end,
		-- config = function()
		-- 	require("kanagawa").setup({
		-- 		colors = {
		-- 			all = {
		-- 				ui = {
		-- 					bg_gutter = "none",
		-- 				},
		-- 			},
		-- 		},
		-- 	})
		-- end,
	},
}
```

**Comment by rebelot** [comment]
@maconsuckow you're missing the `theme` field:

```lua
require("kanagawa").setup({
  colors = { theme = { all = { ui = { bg_gutter = "none" } } } }
)
```

**Comment by maconsuckow** [comment]
@rebelot Whoops, thanks for the response!
