### ISSUE TITLE
`:KanagawaCompile` only works after restarting neovim

### ISSUE THREAD

**Issue by heygarrett** [rebelot/kanagawa.nvim#106]
I tried to set up an autocommand to automatically run `:KanagawaCompile` after saving, but it doesn't update the loaded colorscheme:

```lua
vim.api.nvim_create_autocmd("BufWritePost", {
	group = vim.api.nvim_create_augroup("kanagawa", { clear = true }),
	pattern = "kanagawa.lua",
	callback = function() vim.cmd.KanagawaCompile() end,
})

```

Only after I quit and re-open neovim does the command work to update the colorscheme.

I'm on the [latest commit](https://github.com/rebelot/kanagawa.nvim/commit/002b624d77b0a2f82005a82976a50cde637f8ad1) and I'm using lazy.nvim.

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

**Comment by rebelot** [comment]
This does not work because you need to tell lazy to re-source your config

**Comment by heygarrett** [comment]
lazy.nvim doesn't seem to have a documented way to do that. Do you know how I might? Or is there another way to remove the need to run `:KanagawaCompile` manually?

I'd love to be able to just restart neovim and have the changes to my kanagawa config take effect automatically. Isn't that how it used to work?

**Comment by heygarrett** [comment]
I found an alternative that doesn't require an autocmd: adding `vim.schedule(vim.cmd.KanagawaCompile)` after setting the colorscheme. You can see it on line 20 in this gif:

![CleanShot 2023-03-04 at 17 51 15](https://user-images.githubusercontent.com/1154912/222932264-5751cf95-f4b7-42d2-84a9-b164108aca99.gif)

This shows the color of the `return` keyword being changed with nothing but a change to the config and a restart of neovim.

**Comment by rebelot** [comment]
The whole point of compilation is to reduce startup time. You shouldn't really run compile at each startup... as you're basically doubling the work done by the plugin

**Comment by heygarrett** [comment]
Can I opt out of compilation altogether? 😅 I can appreciate the work you've done to improve startup time, but I didn't have an issue with kanagawa's startup time previously; all that's changed for me is needing to remember to run a new command.

**Comment by rebelot** [comment]
It's not possible at the moment, but may I ask how often are you planning to make changes to kanagawa config? I guess you can safely forget all about this after you find a satisfying setup

**Comment by nullchilly** [comment]
Someone who often switch between transparent and solid background might not like this.

**Comment by catgoose** [comment]
> lazy.nvim doesn't seem to have a documented way to do that. Do you know how I might? Or is there another way to remove the need to run `:KanagawaCompile` manually?
> 
> I'd love to be able to just restart neovim and have the changes to my kanagawa config take effect automatically. Isn't that how it used to work?

I have Lazy.nvim setup this way:

```lua
return {
	"rebelot/kanagawa.nvim",
	lazy = false,
	priority = 1000,
	config = config,
	build = "KanagawaCompile",
}
```

When I restart neovim, Kanagawa updates any changes.  Lazy profile shows no difference in startup time with build or without.

**Comment by sho-87** [comment]
@catgoose I tried adding the build option, but it only seems to affect some highlights and not all. For example adding `ui = { bg_gutter = 'none' } ` to the `colors.theme` option (#104) requires a recompile

**Comment by heygarrett** [comment]
> I guess you can safely forget all about this after you find a satisfying setup

That's actually what I want to avoid; the commands I need frequently aren't the problem. It's the infrequent commands, that become difficult to remember, that I'll do anything to avoid needing.
