### ISSUE TITLE
LineNr color not matching background color for transparent bg since last update

### ISSUE THREAD

**Issue by bellini666** [rebelot/kanagawa.nvim#112]
![image](https://user-images.githubusercontent.com/134025/222965769-eadefdee-202a-48a2-84a8-15e2195079fa.png)

The LineNr used to be the same color as the background when setting it to transparent

**Comment by bujesse** [comment]
I also like my LineNr to be the same as the bg, so I just changed this option (lazy.nvimconfig): 
![image](https://user-images.githubusercontent.com/23506992/222995922-1ac6bf55-14e5-40e6-9e5c-7466f34138df.png)

You can find the colors in `lua/kanagawa/colors.lua`

**Comment by yujinyuz** [comment]
I just encountered this issue and I've added this in my config..

I've set LineNr and SignColumn to `NONE`

```lua
  {
    'rebelot/kanagawa.nvim',
    lazy = false,
    priority = 1000,
    config = function()
      require('kanagawa').setup {
        globalStatus = true,
        overrides = function(colors)
          return {
          FloatBorder = { bg = 'NONE' },
          NormalFloat = { bg = 'NONE' },
          LineNr = { bg = 'NONE'},
          SignColumn = { bg = 'NONE'},
        }
        end,
      }
      vim.cmd.colorscheme('kanagawa')
    end,
  },
```
