### ISSUE TITLE
Help in changing the CusrLineNr 

### ISSUE THREAD

**Issue by DMunkei** [rebelot/kanagawa.nvim#117]
[
![image](https://user-images.githubusercontent.com/17084284/223829693-d0a58609-7762-468f-9577-606509d9bd90.png)
](url)
Can't get the colour to change how I want it to 
```lua
    overrides = function(colors) -- add/modify highlights
        return {
            LineNr = { fg = "#C0A36E", bg = "NONE"},
            CursorLineNr = { fg = colors.sakuraPink, bg = "NONE"},
        }
    end,
```

**Comment by rebelot** [comment]
It would be colors.palette.sakuraPink
