### ISSUE TITLE
Help setting LSP Signature Help Floating window to have  round corners.

### ISSUE THREAD

**Issue by DMunkei** [rebelot/kanagawa.nvim#118]
I had it that the floating window was round. This doesn't seem to be the case anymore. 
[
![image](https://user-images.githubusercontent.com/17084284/223844472-e0efe7cd-02b1-416c-8477-016ad71cab23.png)
](url)

**Comment by rebelot** [comment]
I don't get it. Configure your borders to your liking in lsp hover

**Comment by DMunkei** [comment]
It was working fine until the upgrade.

**Comment by rebelot** [comment]
Are you sure kanagawa is the only thing you updated?

From your screenshot I can clearly see that your float window borders are set to "none". This colorscheme does nothing to float win borders except setting the FloatBorder hlgroup
