### ISSUE TITLE
Completion popup has borders and shifted text

### ISSUE THREAD

**Issue by sho-87** [rebelot/kanagawa.nvim#119]
I'm not sure what is happening here, but nvim-cmp popups seem to have missing text/shifted text/strange borders:

![image](https://user-images.githubusercontent.com/5199715/224010638-4c6e7aeb-c86a-4a87-9966-316e39afd44a.png)

These are my settings for the theme:
https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/theme-kanagawa.lua

The biggest change I made was transplant all the UI element colours from wave into dragon, so I have the blue background with the more muted syntax colours. Not sure how/why that would cause border elements to show up inside popups tho...

**Comment by rebelot** [comment]
Indeed it should not.

**Comment by sho-87** [comment]
closing as I think the problem lies elsewhere in my config
