### ISSUE TITLE
Help setting NormalFloat 

### ISSUE THREAD

**Issue by DMunkei** [rebelot/kanagawa.nvim#120]
I'm close to getting the hover window looking proper. I'm not sure how I can make it have the same colour inside of the window?
[
![image](https://user-images.githubusercontent.com/17084284/224131456-76be50b1-e7b5-4bee-bb61-67661c0afd62.png)
](url)

**Comment by DMunkei** [comment]
I'm not really sure why you closed this without commenting at all, is this to trivial to be worth an issue? 😂

**Comment by rebelot** [comment]
You may want to override `NormalFloat` hlgroup.

**Comment by DMunkei** [comment]
I placed in the image right under the open floating window that  `FloatBorder`, `NormalFloat` are being set to something.

```lua
FloatBorder = { bg = "NONE" }
NormalFloat = { bg = "NONE" }
```
 
What would you rather get to show that there's more effort being made in a post? 

This is a genuine question, not trying to word it rude/offensive.

**Comment by rebelot** [comment]
Can't reproduce... I guess something is overriding your highlights? btw, if you allow compilation, always remember to run `:KanagawaCompile`

try

```
:verbose hi NormalFloat
```

<img width="710" alt="Screenshot 2023-03-10 at 17 12 15" src="https://user-images.githubusercontent.com/36300441/224366505-4480f54e-7806-4a8f-9215-04ee46a10595.png">


> I placed in the image right under the open floating window that `FloatBorder`, `NormalFloat` are being set to something

I did not notice that, perhaps you should emphasize more relevant information. I am sorry anyway, as missing this information slightly tilted me towards the impression that you were asking which hlgroups are responsible for floating window background.

**Comment by DMunkei** [comment]
> I did not notice that, perhaps you should emphasize more relevant information. I am sorry anyway, as missing this information slightly tilted me towards the impression that you were asking which hlgroups are responsible for floating window background.

No worries, happens to us all :) Anyways, this is the output to your suggested command I should try:
 `:verbose hi NormalFloat` [
![image](https://user-images.githubusercontent.com/17084284/224448505-dc8e9746-da44-4949-b040-9372ce4da0d9.png)
](url)
> Can't reproduce... I guess something is overriding your highlights? btw, if you allow compilation, always remember to run 

I've got that set to `false`. This is my entire setup file
```lua
vim.opt.laststatus = 3
vim.opt.fillchars:append({
    horiz = '━',
    horizup = '┻',
    horizdown = '┳',
    vert = '┃',
    vertleft = '┨',
    vertright = '┣',
    verthoriz = '╋',
})
-- Default options:
require('kanagawa').setup({
    compile = false,             -- enable compiling the colorscheme
    undercurl = true,            -- enable undercurls
    commentStyle = { italic = true },
    functionStyle = {},
    keywordStyle = { italic = true},
    statementStyle = { bold = true },
    typeStyle = {},
    transparent = false,         -- do not set background color
    dimInactive = true,          -- dim inactive window `:h hl-NormalNC`
    terminalColors = true,       -- define vim.g.terminal_color_{0,17}
    colors = {                   -- add/modify theme and palette colors
        palette = {},
        theme = {
            all = {
                ui = { bg_gutter = "none" }
            },
        },
    },
    overrides = function(colors) -- add/modify highlights
         local theme = colors.theme
        return {
            TelescopeTitle = { fg = theme.ui.special, bold = true },
            TelescopePromptNormal = { bg = theme.ui.bg_p1 },
            TelescopePromptBorder = { fg = theme.ui.bg_p1, bg = theme.ui.bg_p1 },
            TelescopeResultsNormal = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m1 },
            TelescopeResultsBorder = { fg = theme.ui.bg_m1, bg = theme.ui.bg_m1 },
            TelescopePreviewNormal = { bg = theme.ui.bg_dim },
            TelescopePreviewBorder = { bg = theme.ui.bg_dim, fg = theme.ui.bg_dim },


            Pmenu = { fg = theme.ui.shade0, bg = theme.ui.bg_p1 },
            PmenuSel = { fg = "NONE", bg = theme.ui.bg_p2 },
            PmenuSbar = { bg = theme.ui.bg_m1 },
            PmenuThumb = { bg = theme.ui.bg_p2 },

            FloatBorder = { bg = "NONE" },
            NormalFloat = { bg = "NONE" },
            LineNr = { fg = "#C0A36E", bg = "NONE"},
            CursorLineNr = { fg = colors.palette.sakuraPink, bg = "NONE"},
            -- Visual = { fg = "NONE", bg = colors.palette.lightBlue},
        }
    end,
    theme = "wave",              -- Load "wave" theme when 'background' option is not set
    background = {               -- map the value of 'background' option to a theme
        dark = "wave",           -- try "dragon" !
        light = "lotus"
    },
})

-- setup must be called before loading
vim.cmd("colorscheme kanagawa")

-- vim.api.nvim_set_hl(1, "Linenr", {bg = "none", fg = "#C0A36E"})
vim.cmd [[highlight IndentBlanklineContextStart guisp=#FF0000 gui=underline]]
```
Perhaps this might help? I'm clueless :/

**Comment by DMunkei** [comment]
I did however notice, if I go inside of the floating window, then the colour seems to be the correct colour...?
[
![image](https://user-images.githubusercontent.com/17084284/224449190-239bffd0-7af9-4f87-b1c6-34dd080976c2.png)
](url)

Ah while, trying this out, I found out why it's not working properly... So apparently if I have `dimInactive = true` it behaves like before. When I have it set to `false` then it works normally.  I tried this option with `compile` set to both `true` and `false` this had no affect. It's completely dependant on the `dimInactive` property. :D 

Here is the same hover with `dimInactive` and `compile` set to `false`.
[
![image](https://user-images.githubusercontent.com/17084284/224450119-eb2934d7-7e61-42b9-8ace-a721f180dea6.png)
](url)
 Here `dimInactive` is set to `true` and `compile` is `false`.
[
![image](https://user-images.githubusercontent.com/17084284/224450418-e52e40ea-7487-4e51-a9cf-2415c9cce59f.png)
](url)
Not sure why it behaves like this? I'm using Alacritty as my terminal emulator, if that might with the debugging.
