### ISSUE TITLE
Incorrect (as per config) formatting on `self`, `this` and `return`.

### ISSUE THREAD

**Issue by JustinStitt** [rebelot/kanagawa.nvim#124]
Suddenly, italics have appeared back into my Kanagawa setup! I really dislike italics so I disabled them when I first switched (~2 weeks ago). I use Lazy Package manager w/ LunarVim and it recently auto-updated Kanagawa to > 3579d55c47366a536e07cf83df397a9f5f806813 <. 

I've attached a screenshot below of my editor:

![image](https://user-images.githubusercontent.com/24460581/224433477-f89a069e-a872-423c-b87c-09c370af7e2e.png)

Notice also the `return` keyword has special highlighting even though my config (below) clearly shows that option disabled!

Here's my config:
```lua
lvim.colorscheme = "kanagawa"

require('kanagawa').setup({
  compile = true,
  undercurl = false, -- enable undercurls
  commentStyle = { italic = false },
  functionStyle = { bold = true },
  keywordStyle = { italic = false },
  statementStyle = { bold = true },
  typeStyle = {},
  variablebuiltinStyle = { italic = false },
  specialReturn = false, -- special highlight for the return keyword
  dimInactive = true,
  colors = {
    theme = {
      all = {
        ui = {
          bg_gutter = "none"
        }
      }
    }
  }
})

```

Note: I am using the `compile` option and I **am** using :KanagawaCompile after any change.

**Comment by JustinStitt** [comment]
I guess it should be noted, it's not ALL keywords that are italics. Just seems like `self` in Python3. Meanwhile, the `return` keyword in all languages is a different color than other keywords.

**Comment by JustinStitt** [comment]
Same issues in C++ but with `this` instead of `self`

![image](https://user-images.githubusercontent.com/24460581/224434615-7c345c04-779a-4c3f-be1d-efc6e6554075.png)

**Comment by JustinStitt** [comment]
~~Fixed~~ Remedied (*temporarily*) by specifying [this commit](https://github.com/rebelot/kanagawa.nvim/commit/de7fb5f5de25ab45ec6039e33c80aeecc891dd92) in Lazy 
```lua
lvim.plugins = {
  { "rebelot/kanagawa.nvim", commit = "de7fb5f" },
}
```

as per https://github.com/rebelot/kanagawa.nvim/issues/104#issuecomment-1454859457
```> I'm glad lazy.nvim allows me to specify commits. I may be `commit = "de7fb5f",` forever.```

**Comment by rebelot** [comment]
Go cattppuccin and don't even bother
