### ISSUE TITLE
Operators, RegEx used to be boatYellow2 yellow

### ISSUE THREAD

**Issue by fdelacruz** [rebelot/kanagawa.nvim#125]
boatYellow2 (#C0A36E)
<img width="120" alt="Screen Shot 2023-03-15 at 4 15 44 PM" src="https://user-images.githubusercontent.com/148098/225286451-ab1fd127-f6aa-455f-9336-8e98abf82bde.png">

Now it appears to be autumnRed (#C34043) used for Git Delete
<img width="119" alt="Screen Shot 2023-03-15 at 4 24 50 PM" src="https://user-images.githubusercontent.com/148098/225288502-a3e99e1e-9bc0-4fc6-867f-982be16f17a6.png">

This is in all three themes.

Thanks

**Comment by rebelot** [comment]
What do you mean? Syntax elements did not change. Are you referring to the lualine integration?

**Comment by fdelacruz** [comment]
Yes, this is suddenly happening in lualine.

**Comment by fdelacruz** [comment]
The change happened in commit [5173878](https://github.com/rebelot/kanagawa.nvim/commit/5173878eb6bea1bc50f01e143fc08db3c022cf6a) 
<img width="1325" alt="Screen Shot 2023-03-15 at 8 55 31 PM" src="https://user-images.githubusercontent.com/148098/225365063-f3de5156-6441-402c-b7a8-755affb38ccd.png">

**Comment by rebelot** [comment]
Is it that bad?

**Comment by cbochs** [comment]
I for one do find the red distracting and preferred the original colour

**Comment by fdelacruz** [comment]
boatYellow2 gives me such a warm and fuzzy feeling.

**Comment by benfrain** [comment]
Oh man, I loved the new red color! Came hear to find why it was yellow again! Felt like the red suited the seriousness of issuing a command 😆

**Comment by benfrain** [comment]
If I want to override the yellow one on my personal config and have it back on the red, where is the 'best' place to be doing that? 

Is there some place in my setup I can put

```lua
          command = {
            a = { bg = theme.vcs.removed, fg = theme.ui.bg },
            b = { bg = theme.ui.bg, fg = theme.vcs.removed },
          },
```

?
