### ISSUE TITLE
nvim-cmp preview colors seem to not be from the colorscheme

### ISSUE THREAD

**Issue by lokesh-krishna** [rebelot/kanagawa.nvim#128]
![image](https://user-images.githubusercontent.com/20235646/227076220-0552d7c8-6049-4c22-b561-8f3199b11bf1.png)

Preview for nvim-cmp completions do not seem to be using the kanagawa colorscheme. Is this simply how nvim-cmp previews work or did I miss some setting for either nvim-cmp or kanagawa?

**Comment by rebelot** [comment]
I have no clue what hlgroups is the doc preview showing, I guess it might be some R plugin you're using?

**Comment by lokesh-krishna** [comment]
Is there a way for me to find out? I'm using the [Nvim-R](https://github.com/jalvesaq/Nvim-R) plugin.

**Comment by rebelot** [comment]
I quickly searched the repo for highlight definitions, https://github.com/search?q=repo%3Ajalvesaq%2FNvim-R+hi+def&type=code

you might want to make sure that Kanagawa is loaded and set up __before__ everything else, this might have an effect on this plugin
