### ISSUE TITLE
Kanagawa light mode

### ISSUE THREAD

**Issue by Kypert** [rebelot/kanagawa.nvim#13]
Hi, I am currently enjoying the dark colorscheme, just wondering if there are any plans regarding a light mode for those sunny days?

**Comment by rebelot** [comment]
yes my friend. I have recently added the support for themes, so expect more to come :)

**Comment by JSchrtke** [comment]
Are you working on this? If not, I would give it a shot based on the color palette you use for the dark theme.

**Comment by rebelot** [comment]
Hi! Yes it's been some time. I am not currently working on this, but I have playing with kanagawa.themes in my todo list. If you want to experiment with this, I'd suggest adding a new theme. The names in the default themes are the ones required to setup the highlights

**Comment by JSchrtke** [comment]
Yeah, I've played around a bit earlier. Creating a light theme with the existing palette is proving a bit tricky though, because lot's of the colors in there are lacking a bit of contrast on a bright background.

I'll play around some more; once I get something I'm happy with I'll leave you a pull request.

**Comment by sseneca** [comment]
Any progress on this? I've found myself wanting it more and more as of late :)

**Comment by bakunowski** [comment]
I've been playing around with a light mode recently. Here are the results:
<img width="1512" alt="Screenshot 2022-08-03 at 19 41 33" src="https://user-images.githubusercontent.com/45123458/182685107-40f4443b-16c6-46ce-a0a0-2a3e450e7424.png">


Curious to hear if this is what others envisioned for the light version of this theme.

**Comment by JSchrtke** [comment]
I'm not sure what I "envisioned", but I sure gave it a good try. My original idea was to keep the original palette, and just use those colours to make a light theme, but I had many issues with contrast.
So I started adding more colors that kinda "looked right". But at some point I felt I was making a new theme, and I did not want to just make something that wasn't up to the original authors idea/inspiration of the great wave painting. I shelved it at some point. Just had a look again, this was the last I came up with:

![image](https://user-images.githubusercontent.com/31078741/182707795-aa960a3e-d23b-4e57-9aef-207b5c1aa5ab.png)

**Comment by rebelot** [comment]
That isn't bad at all! After some experiments my idea is the following:
- Invert bg and fg
- Use the same tints of colors for syntax elements but adjust their luminance in HSL
- add the missing white/gray shades for UI elements

Now I'm just wondering if it's worth it to include an HSL module and handle shading on the fly or just add the new colors (maybe with a bit of name refactoring)

**Comment by rebelot** [comment]
still need serious tweakings but that's the general idea.

<img width="1277" alt="Screenshot 2022-08-09 at 12 37 59" src="https://user-images.githubusercontent.com/36300441/183628537-28c4a344-68de-47d6-86f2-35974e9d040e.png">

**Comment by sseneca** [comment]
That looks pretty good! When are you thinking of releasing it? Maybe it could be on a separate branch for now, so people could opt-in to test it for a while :)

Or that may be unnecessary as it's enabled/disabled by the user anyway

**Comment by mavam** [comment]
Honestly, merging *something* is better than nothing. Even though it ain't pretty enough, I'd rather stay outside than go inside just because I don't have a light colorscheme. 😉

**Comment by rebelot** [comment]
fair enough, I am working on it atm but for now it has it's own slightly outdated branch https://github.com/rebelot/kanagawa.nvim/tree/light_theme

**Comment by sseneca** [comment]
Which option do I need to set to use it? I have that branch checked out

**Comment by rebelot** [comment]
> Which option do I need to set to use it? I have that branch checked out

add `theme = "light"` option to your setup config

**Comment by rebelot** [comment]
light_theme branch has been deleted, please update to see a first attempt on light theme on master. Expect some (many) changes in the near future. I hope you can enjoy it :)

**Comment by mavam** [comment]
Is there a way to dump the color hexcodes for the light scheme? I realized that I also need to update my Kitty theme for it to be useful.

**Comment by rebelot** [comment]
> Is there a way to dump the color hexcodes for the light scheme? I realized that I also need to update my Kitty theme for it to be useful.

```lua
:lua =require"kanagawa.themes".light(require"kanagawa.colors".setup({theme = "light"}))
```

**Comment by mavam** [comment]
Thanks, got it to work:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/53797/185036647-e8350898-16d1-4704-b616-6057ecde151c.png">

<img width="861" alt="image" src="https://user-images.githubusercontent.com/53797/185036845-3ac72569-ebe9-44a3-b69e-f94358a1d88f.png">

Here's the theme file I used for Fish:

```
## name: Kanagawa-Light
## license: MIT
## author: Matthias Vallentin


background #f2eccd
foreground #3b3b4c
selection_background #c8cfd9
selection_foreground #16161D
url_color #72A7BC
cursor #16161D

# Tabs
active_tab_background #c8cfd9
active_tab_foreground #3b3b4c
inactive_tab_background #b3bac4
inactive_tab_foreground #727169
#tab_bar_background #15161E

# normal
color0 #090618
color1 #C34043
color2 #76946A
color3 #69542e
color4 #284683
color5 #493764
color6 #4a6860
color7 #16161D

# bright
color8  #727169
color9  #aa1212
color10 #4d652f
color11 #725217
color12 #295364
color13 #938AA9
color14 #5d5573
color15 #3b3b4c

# extended colors
color16 #FFA066
color17 #FF5D62
```

I went through the original (dark) file and looked for the hex codes in the output of the command you posted, @rebelot.

**Comment by sseneca** [comment]
Shall I use this thread to discuss issues I've noticed with the light theme, or shall I create new issues for each?

**Comment by rebelot** [comment]
Doesn't really matter. Please address the issues you have found

**Comment by sseneca** [comment]
There are a couple things, I don't have time to list them right now but the main issue I've noticed is that some colours seem incorrect, e.g. this is what fzf-lua's picker looks like:

![Screenshot 2022-08-19 at 10 19 49](https://user-images.githubusercontent.com/25619071/185587763-4e1fb4d0-1dbf-43ed-b672-ec8aa454ecec.png)

Same happens in Kitty using fzf:

![Screenshot 2022-08-19 at 10 21 29](https://user-images.githubusercontent.com/25619071/185587993-ec7327b9-5826-4cbb-899a-44e90c2a88a4.png)

This is much less jarring in the dark version of the theme:

![Screenshot 2022-08-19 at 10 22 34](https://user-images.githubusercontent.com/25619071/185588251-7a8cac8e-4159-4d5a-9f79-367e426e28b9.png)

**Comment by rebelot** [comment]
this is due to fzf color scheme, I think you should use `fzf --color=light`. See https://github.com/junegunn/fzf/wiki/Color-schemes

**Comment by sseneca** [comment]
Hmm, that looks a bit better, but still not as good as the dark theme? Unless it's meant to look like that, and I'm just not used to it...

![Screenshot 2022-08-19 at 14 39 25](https://user-images.githubusercontent.com/25619071/185631300-36b69dc7-e181-4a4a-8dd0-1989e1cbd01e.png)

**Comment by rebelot** [comment]
<img width="267" alt="Screenshot 2022-08-19 at 18 10 26" src="https://user-images.githubusercontent.com/36300441/185661502-9afe292a-70c7-4bf0-98b0-a2fc2cd06559.png">
<img width="224" alt="Screenshot 2022-08-19 at 18 10 03" src="https://user-images.githubusercontent.com/36300441/185661506-e761b7b1-dd37-4cec-9450-7b44dbeb922f.png">

one is gruvbox (light hard), the other is kanagawa.

**Comment by strash** [comment]
Hi!
Are there any plans to implement theme selection with `vim.opt.background = "light"/"dark`?

**Comment by DMunkei** [comment]
Is there a way to toggle between the dark and light mode?  I set the background using `:set background=light`

I'm using Alacritty, when I open a window for example like telescope, the theme is adjusted. However, when I'm inside of a buffer the old theme is still active...?
The Preview window shows the file `colours.lua` correctly rendered
[![image](https://user-images.githubusercontent.com/17084284/189641512-51aee412-0f73-487d-ad11-185381016a75.png)](url)
When I load it into the buffer, it's back to the dark theme
[![image](https://user-images.githubusercontent.com/17084284/189641366-b9f2c3fa-7344-43bc-a6b4-9ce566dd5f01.png)](url)

Thanks for your help people :)

**Comment by rebelot** [comment]
sorry but I can't reproduce... do you have any plugins that might interfere with colorschemes? did you hardcode kanagawa highlights anywhere?

**Comment by DMunkei** [comment]
No I haven't hard coded colorschemes anywhere. This is my color file

```
vim.opt.laststatus = 3
vim.opt.fillchars:append({
    horiz = '━',
    horizup = '┻',
    horizdown = '┳',
    vert = '┃',
    vertleft = '┨',
    vertright = '┣',
    verthoriz = '╋',
})

require('kanagawa').setup({
    undercurl = true,           -- enable undercurls
    commentStyle = { italic = true },
    functionStyle = {},
    keywordStyle = { italic = true},
    statementStyle = { bold = true },
    typeStyle = {},
    variablebuiltinStyle = { italic = true},
    specialReturn = true,       -- special highlight for the return keyword
    specialException = true,    -- special highlight for exception handling keywords
    transparent = true,        -- do not set background color
    dimInactive = true,        -- dim inactive window `:h hl-NormalNC`
    globalStatus = true,       -- adjust window separators highlight for laststatus=3
    terminalColors = true,      -- define vim.g.terminal_color_{0,17}
    colors = {},
    overrides = {},
    theme = "default"           -- Load "default" theme or the experimental "light" theme
})

vim.cmd("colorscheme kanagawa")
```
The problem is after I swap from dark to white. The buffer remains in dark mode, but if I open a new buffer and it's currently active, it renders using the dark theme.
[
![image](https://user-images.githubusercontent.com/17084284/189678391-afd662c1-5991-4da4-8acb-d89995d2361a.png)
](URL)
The last picture I'm inside of the right buffer, and the left buffer is using the light theme...

**Comment by rebelot** [comment]
I just noticed you are using transparent background and dimInactive feature. For this you must also set an appropriate background for your terminal theme, as the current buffer has no background (what you see is your terminal background color)

**Comment by DMunkei** [comment]
Ah okay, I'm pretty much a noob here, how do I see the background? What would be appropriate here?

**Comment by rebelot** [comment]
Either remove the transparency option or set an appropriate theme for the terminal

**Comment by DMunkei** [comment]
That worked, by setting the transparency to false. I have a question about the dragon theme. Is it possible to try now? I set 'dragon' in the theme field, but didn't notice any change.

**Comment by DMunkei** [comment]
Silly question, but how do I unset the `background`? I tried doing `:set background=""` but that did nothing.

**Comment by dzintars** [comment]
![image](https://user-images.githubusercontent.com/547420/203606217-76a99077-1419-47bc-a70f-92a379ca8dfa.png)
I would say that `comment` and/or `listchar` wants a little bit more contrast.

**Comment by Kypert** [comment]
Hey @rebelot, I saw a lot of commotion about breaking changes, so I took the time to update and realized I should step by here and let you know that I have happily been rocking the light/lotus variant for months now. So feel free to close this ticket, unless you have more modifications in mind :)
