### ISSUE TITLE
ALE warning/error signs have background and a little messy

### ISSUE THREAD

**Issue by sk8higher** [rebelot/kanagawa.nvim#131]
I use kanagawa-dragon, and when I get warnings or errors on ALE they have their own background in line and warning sign become messed. Is this a theme problem or my config? 
![Screenshot_20230401_162942](https://user-images.githubusercontent.com/30351533/229292139-cff34575-82e0-46aa-a93c-a7c259831bf1.png)

How it looks in other theme: (seoul256)
![Screenshot_20230401_162953](https://user-images.githubusercontent.com/30351533/229292184-ec6f2c00-b451-4450-b706-b260d87b967a.png)

**Comment by rebelot** [comment]
I do not use ALE, since I think lsp + null-ls provide a more consistent environment. Anyway, kanagawa defines the standard nvim  `DiagnosticSign*` hl groups. You should look which hlgroup is used by ale to highlight diagnostic signs and link it to the default ones

**Comment by sk8higher** [comment]
This made it work (vimscript)
```
augroup colorscheme_override
  autocmd!
  autocmd colorscheme kanagawa-dragon
    hi link ALEErrorSign error
    hi link ALEWarningSign todo
    hi error guifg=#e46876 guibg=#282727
    hi todo guifg=#e6c384 guibg=#282727
augroup end
```
![image](https://user-images.githubusercontent.com/30351533/229613581-c031539b-d94e-4a7b-a853-bb929327e66d.png)
