### ISSUE TITLE
Add treesitter highlight groups, f. i. `@text.diff.add`

### ISSUE THREAD

**Issue by PhilippFeO** [rebelot/kanagawa.nvim#135]
Hey rebelot,

via 
```lua
require('kanagawa').setup({
    ...,
    overrides = function(colors)
        return {
            -- Assign a static color to strings
            String = { fg = colors.palette.carpYellow, italic = true },
            -- theme colors will update dynamically when you change theme!
            SomePluginHl = { fg = colors.theme.syn.type, bold = true },
        }
    end,
    ...
})
```
I can add/modify highlight groups. How does it work for treesitter highlight groups like `@text.diff.add`?

Thank you and have a nice weekend! :)

**Comment by Rattko** [comment]
Hey @PhilippFeO,

I have these lines in my `init.vim`

```lua
require('kanagawa').setup({
    ...,
    overrides = function(colors)
        return {
            ...,
            ['@text.todo'] = { fg = colors.theme.diag.error, bg = 'none' },
            ['@text.note'] = { fg = colors.theme.diag.hint, bg = 'none' }
        }
    end,
    ...
})
```

Hope this helps!

**Comment by PhilippFeO** [comment]
Hey @Rattko,

your proposal helped me (thanks a lot! 🥳) in that sense, that I forgot `return { … }` (embarassing :D) but using
```lua
overrides = function(colors)
    return {
        ['@text.diff.add'] = { fg = colors.theme.diff.add },
        ['@text.diff.delete'] = { fg = colors.theme.diff.delete }
    }
end
```
also doesn't help.

With
```lua
vim.api.nvim_set_hl(0, "@text.diff.add", { fg = '#229922' })
vim.api.nvim_set_hl(0, "@text.diff.delete", { fg = '#cc4444' })
```
everything works as expected.

Some background information (in case you are curious): I want to use these highlights in `filetype=diff` buffers (to be precise when using `git add --patch` and/or `git commit -v`. I have Treesitter installed, as well as the according `diff` and `gitcommit` modules but theses buffers stay blank, although the filetype is detected. I can manually turn on the Treesitter highlighting with `:TSToggle highlight (diff|gitcommit)` but I am not yet familiar with Treesitter, so I can't fix the problem of blank `diff` and `gitcommit` buffers with Treesitter's internal mechanics and was/am trying to find a workaround. One is to enable `@text.diff.(add|delete)` (this was suggested in some Treesitter issues) which are disable by default as I saw when I inspected kanagawa's source code. Because it didn't/doesn't work with kanagawa's `overrides` feature, I typed the two `nvim_set_hl(…)` lines and opened this issue. Sadly, it's a workaround for the workaround, hence I am not happy with the solution and seek a possibility directly using kanagawa's setup.

**Comment by rebelot** [comment]
If you use compilation, remember to run `:Kanagawacompile` after modifying your config

**Comment by PhilippFeO** [comment]
I don't use compilation :/

**Comment by rebelot** [comment]
can you verify the output of `:hi @text.diff.add` after you configure the overrides? the two hlgroups are set as expected for me. Anyway, I'll be adding those groups by default

**Comment by PhilippFeO** [comment]
Sure! :)

Output of `:hi @text.diff.add` with configured `overrides`:
```
E411: highlight group not found: @text.diff.add
```

Output of `:hi @text.diff.add` with `vim.api.nvim_set_hl(0, "@text.diff.add", { fg = '#229922' })` [1]:
```
:hi @text.diff.add
@text.diff.add xxx guifg=#229922
```

---

I have pulled the recent commit and the `add`/`delete` lines are highlighted by default. Sadly, I am still not able to set the highlight group via `overrides`:
```lua
overrides = function(colors)
    return {
        ['@text.diff.add'] = { fg = "#229922" },
        ['@text.diff.delete'] = { fg = colors.theme.diff.delete }
    }
end
```
omits its preset
```
:hi @text.diff.add
@text.diff.add xxx guifg=#2b3328
```

Last but not least: Thank you for the fast update! In principal I can work with it (so, no wish for further investigation from my side). If you want to dig deeper and need my outputs: Tell me, I will provide them and assist as best as I can!

**Comment by rebelot** [comment]
This is very odd... this works for me
```lua
    {
        "rebelot/kanagawa.nvim",
        lazy = false,
        priority = 1000,
        config = function()
            require("kanagawa").setup({
                overrides = function(colors)
                    local theme = colors.theme
                    return {
                        ['@text.diff.add'] = { fg = "green" },
                        ['@text.diff.delete'] = { fg = "red" }
                    }
                end,
            })
    }
```

**Comment by PhilippFeO** [comment]
Now, I have found my (naive) mistake... And I feel uncomfortable because you spent your spare time helping me. I am very sorry!

The explanation:
Two months ago, I adapted [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) to lift my beginner init.lua. Since I already used your colorscheme, I switched the line in my new init.lua and left the plugin specification as it was, i. e.
```lua
{
  'rebelot/kanagawa.nvim', -- default: 'navarasu/onedark.nvim'
  priority = 1000,
  config = function()
    vim.cmd.colorscheme 'kanagawa'
  end,
},
```
Of course I didn't check this piece of code while experimenting with `@text.diff.add` which I do/did in a separate `setup()` call in `after/plugin/kanagawa.lua` and since this file is loaded after the execution of `vim.cmd.colorscheme 'kanagawa'` nothing happens.

Please condemn me! :o
Your excerpt helped me, because I also use lazy.nvim and wanted to try your code as it is. After opening the file, I read `vim.cmd.colorscheme 'kanagawa'` and now I am writing this post.

**Comment by rebelot** [comment]
No worries:) glad the issue is solved.

You nonetheless pointed out two hlgroups that should have been defined
