### ISSUE TITLE
Disable number line background

### ISSUE THREAD

**Issue by ehaynes99** [rebelot/kanagawa.nvim#136]
First off, thanks for the great theme!

I recently updated kanagawa (previously `4c8d48726621a7f3998c7ed35b2c2535abc22def`), and now the number lines are a different color than the background, which I would like to remove. It seems to be the `sumiInk4` color, and the only 2 things using that are `bg_gutter` and `bg_p1`. However, overriding those in the theme doesn't have any effect:
```lua
theme = {
  wave = {
    bg_gutter = 'none',
    bg_p1 = 'none',
  },
},
```
Any idea how I can make it simply match the background in the editor (potentially dimmed)?

#### Before
![image](https://user-images.githubusercontent.com/2187664/230663685-ce08c6f9-7a05-4a65-a025-47a6e36ff090.png)

#### After
![image](https://user-images.githubusercontent.com/2187664/230664622-29825124-f3f7-42bd-8f11-630567ff9116.png)

**Comment by ehaynes99** [comment]
Of course, immediately after posting, I realized my mistake... Sorry about that.

```lua
theme = {
  wave = {
    ui = { -- WAS MISSING THIS LEVEL
      bg_gutter = 'none',
      bg_p1 = 'none',
    },
  },
},
```

**Comment by rebelot** [comment]
Why remove bg_p1? bg_gutter is the only one you'd probably want to set to "none", or you'll be missing folds highlights

**Comment by ehaynes99** [comment]
I tried both just because they were the only ones using that particular color, but ended up with only the gutter one. Thanks!
