### ISSUE TITLE
Semantic highlighting breaks the colorscheme

### ISSUE THREAD

**Issue by primeapple** [rebelot/kanagawa.nvim#138]
I come from this thread: https://www.reddit.com/r/neovim/comments/12gvms4/this_is_why_your_higlights_look_different_in_90/

When I'm in a Javascript file with `tsserver` running, it looks like this:
![with_semantic_highlighting](https://user-images.githubusercontent.com/35628420/231150265-6eee0b44-5566-4672-af01-10997583848f.png)

When i disable the semantic highlighting:

```
for _, group in ipairs(vim.fn.getcompletion("@lsp", "highlight")) do
  vim.api.nvim_set_hl(0, group, {})
end
```

it looks correct again

![without_semantic_highlighting](https://user-images.githubusercontent.com/35628420/231150501-6202df31-aacc-43b8-b98f-7d3f1caff21c.png)

I'm on Nvim 0.9.

May be related to:
https://github.com/rebelot/kanagawa.nvim/issues/133

**Comment by rebelot** [comment]
what you are referring to as "correct" is just what you were used to. The "correct" highlighting is arguably the one provided by the semantic tokens. Constant variables are highlighted in orange, but if you don't like it, you can override it. take a look at https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/highlights/lsp.lua to see what semantic tokens groups are defined by Kanagawa. you can use the command `:Inspect` to see the highlights for the word under the cursor.

**Comment by rebelot** [comment]
you should not modify or interact with that file in any way, it was just a reference for you to see which semantic highlights are defined by kanagawa on top of the default ones. To override any hlgroup, as mentioned multiple times and in plain sight in the readme, you should use the `override` option:

```lua
            require("kanagawa").setup({
                overrides = function(colors)               
                    return {
                      ["@lsp.typemod.variable.local"] = { link = "@variable" },
                    }
                end,
            })
```

**Comment by primeapple** [comment]
Thank you. I was just trying to understand what is happening internally in kanagawa.

But thank you for your time.

**Comment by rebelot** [comment]
https://github.com/rebelot/kanagawa.nvim/blob/22adef57f08a3cd07978b65966ce68da42501f68/lua/kanagawa/highlights/init.lua#L20

called by

https://github.com/rebelot/kanagawa.nvim/blob/22adef57f08a3cd07978b65966ce68da42501f68/lua/kanagawa/init.lua#L89
