### ISSUE TITLE
wrong colors in neogit diff when selecting a hank

### ISSUE THREAD

**Issue by strash** [rebelot/kanagawa.nvim#139]
https://user-images.githubusercontent.com/14233263/232033773-136f7fcf-4de3-45da-ada1-e68b330bd35c.mov

**Comment by rebelot** [comment]
I'll fix that, could you please provide the names of the relevant hlgroups?

**Comment by strash** [comment]
Hi, thought kanagawa already has neogit support because i didn't have this problem before 🙂

https://github.com/TimUntersberger/neogit#contextual-highlighting

**Comment by rebelot** [comment]
This might not be solved, please let me know if it works. Neogit highlights are a bit of a mystery to me as there are many more than the ones advertised and it's not clear if they do what they should....

**Comment by strash** [comment]
Totally forgot about the "Inspect" feature. Unfortunately this gets us nothing:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/14233263/232088778-d827794c-b16d-43cb-b2b1-2ee963002ca2.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/14233263/232089506-14d5d621-77fc-4422-9024-b4755f10a37c.png">

**Found these ones:**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/14233263/232089902-ccc269c6-db75-4ed6-9dd0-661c8cc1f980.png">

**Comment by strash** [comment]
@rebelot, hi
Could you please add missing Neogit highlights `NeogitDiffAddHighlight` and `NeogitDiffDeleteHighlight`?
