### ISSUE TITLE
Errors in hlgroups.lua

### ISSUE THREAD

**Issue by guigui64** [rebelot/kanagawa.nvim#14]
* `comment` where it should be `fg_comment`:
https://github.com/rebelot/kanagawa.nvim/blob/a7c23b51beb0d232a025eae5f060bfb81b8d1ce0/lua/kanagawa/hlgroups.lua#L30
https://github.com/rebelot/kanagawa.nvim/blob/a7c23b51beb0d232a025eae5f060bfb81b8d1ce0/lua/kanagawa/hlgroups.lua#L60
https://github.com/rebelot/kanagawa.nvim/blob/a7c23b51beb0d232a025eae5f060bfb81b8d1ce0/lua/kanagawa/hlgroups.lua#L384
* `warn` where it should be `warning`:
https://github.com/rebelot/kanagawa.nvim/blob/a7c23b51beb0d232a025eae5f060bfb81b8d1ce0/lua/kanagawa/hlgroups.lua#L67

**Comment by rebelot** [comment]
Good call! thanks
