### ISSUE TITLE
TODO fg color is almost the same as bg in diff view

### ISSUE THREAD

**Issue by kting28** [rebelot/kanagawa.nvim#140]
![image](https://user-images.githubusercontent.com/24449116/232107166-2abbaa4d-4a0f-4acc-8dac-6feeee131551.png)

See above - the "TODO" color is almost the same as the diff addition green background.  Minor pedantic complaint :)

**Comment by kting28** [comment]
yup, just pointing it out FYI, not a big deal. Thanks for the override example.

**Comment by rebelot** [comment]
On Tue, Apr 18, 2023 at 10:57:16AM -0700, Kai Ting wrote:
>yup, just pointing it out FYI, not a big deal. Thanks for the override example.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rebelot/kanagawa.nvim/issues/140#issuecomment-1513582112
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>

that is the default implementation for the mentioned highlight group, if
you come up with a good combination of highlights I'll gladly accept a
PR!
