### ISSUE TITLE
Statement style does not respect configuration option

### ISSUE THREAD

**Issue by manuelcattelan** [rebelot/kanagawa.nvim#145]
Heyo fellow Italian developer :it: First of all, thank you for the amazing colorscheme!

I'm having some issues disabling the bold statement style which comes as a default option, below you can find an example and the configuration of the colorscheme for reference.

Hopefully you can clearly see from the screenshot that boolean statements like _true_ or _false_ render in bold while the statement style option sets `bold = false`.
 
<img width="1486" alt="Screenshot 2023-04-19 alle 21 08 03" src="https://user-images.githubusercontent.com/91598275/233175765-cda78b6b-5dde-4588-be1f-106dbf3a3f85.png">

I feel dumb not understanding why this won't work but I might be missing some configuration basics here..

**Comment by rebelot** [comment]
Hi! Thanks for the cheer up:)

Booleans are not statements tho, you should override the `Boolean` hlgroup using `config.overrides`
HTH

**Comment by manuelcattelan** [comment]
My bad, I gave it for granted that statements also included booleans since it was the only config option that was setting some bold hl. Thanks for the quick reply!
