### ISSUE TITLE
Wrong colors in alacritty terminal?

### ISSUE THREAD

**Issue by turutupa** [rebelot/kanagawa.nvim#147]
Is there any known reason why in alacritty colors are rendered differently? It's pre weird. Fresh install of alacritty btw (alacritty on the left, xfce4terminal on the right)

![image](https://user-images.githubusercontent.com/44581951/236141797-9c8ef640-46ba-4b08-a555-243d8eb3750a.png)

**Comment by elsuizo** [comment]
are you enabled the `env` section in alacritty???

```toml
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color
```

**Comment by turutupa** [comment]
Yep, that was it! Thank you!
