### ISSUE TITLE
`pumblend` handling

### ISSUE THREAD

**Issue by kting28** [rebelot/kanagawa.nvim#148]
In themes like tokyonight, setting `pumblend=30` enables the transparent effect of popups and menus:

![image](https://user-images.githubusercontent.com/24449116/237004598-c09fe1d0-8150-46a1-b5fa-4f10ddf84139.png)

This is not just eye candy since the transparency does help to reveal a bit what's behind the menu. However this doesn't seem to work in kanagawa:

![image](https://user-images.githubusercontent.com/24449116/237004711-c23e5b90-7774-4029-86b2-13c51232f3fe.png)

I tried the "transparency" related hints on README but those doesn't seem to work. Regular command menu transparency is not affected. Any hints on what causes this?

**Comment by rebelot** [comment]
add this override
` Pmenu = { blend = vim.o.pumblend }`

**Comment by kting28** [comment]
Thanks. This worked for the command line menus but the lsp auto-complete popup doesn't seem to be affected. Again with tokyonight, `pumblend` affects both. Is there another override I need to make?

**Comment by rebelot** [comment]
hmm, it works for me.. maybe check if you've some strange win highlight overrides in cmp config

**Comment by kting28** [comment]
Hmm.. I will need to debug a bit by removing other stuff. don't see anything suspicious.  This is probably kanagawa specific since the same cfg works in other themes with pumblend set. Will dig around a  bit.

```
   CmpCompletion  xxx links to Pmenu                   
   CmpCompletionSel xxx guibg=#2d4f67                  
   CmpCompletionBorder xxx guifg=#2d4f67 guibg=#223249 
   CmpCompletionThumb xxx links to PmenuThumb          
   CmpCompletionSbar xxx links to PmenuSbar
```

**Comment by kting28** [comment]
Found issue - turns out related to the `nvim-cmp` provided options to configure bordered window for the completion menu:
```lua
cmp.setup({
  snippet = {
    -- REQUIRED - you must specify a snippet engine
    expand = function(args)
      -- vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
      require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
      -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
      -- require'snippy'.expand_snippet(args.body) -- For `snippy` users.
    end,
  },
  window = {  -- This seems to override blend option
    completion = cmp.config.window.bordered(), 
    documentation = cmp.config.window.bordered(),
  },
```

**Comment by kting28** [comment]
@rebelot 
Sorry another issue - it seems the `winblend` option of telescope [config](https://github.com/nvim-telescope/telescope.nvim/blob/40c31fdde93bcd85aeb3447bb3e2a3208395a868/lua/telescope/config.lua#L214) is not taking effect in kanagawa:

```
require("telescope").setup {
  defaults = {
    mappings = {
      i = {
        ["<esc>"] = actions.close
      },
    },
    winblend=20
  }
}

```

Above works only in tokyonight. I tried overriding a few highlights starting with "Telescope" but can't get it to work. Any hints?

**Comment by kting28** [comment]
Answering my own question here - turns out there's enough hints on the README already:

```lua
 overrides = function(colors)
    local theme = colors.theme
    return {
        Pmenu = { blend = vim.o.pumblend },
        TelescopePromptNormal = { bg = theme.ui.bg_p1, blend = vim.o.pumblend },
        TelescopeResultsNormal = { fg = theme.ui.fg_dim, bg = theme.ui.pmenu.bg, blend = vim.o.pumblend },
        TelescopePreviewNormal = { bg = theme.ui.bg_dim, blend = vim.o.pumblend },
    }
```
