### ISSUE TITLE
Beautiful colorscheme, with a few issues

### ISSUE THREAD

**Issue by ctranstrum** [rebelot/kanagawa.nvim#15]
I have been using kanagawa for about a week now, and I'm really enjoying it, however, I have two things that make me want to move to a different colorscheme:

* the bold orange color for true/false makes me think I have a diagnostic warning in my code every time I see it
* the background color of floating windows (seen for example in pop-up diagnostics) is almost indistinguishable from the regular background color, so it is too difficult to see where it ends

Great work on this!

**Comment by ctranstrum** [comment]
Ah, I see you've already allowed for overrides. I'll just use those!

**Comment by rebelot** [comment]
I'm sorry for your issues, I can suggest you to try 
```lua
require'kanagawa'.setup({
    overrides  = {
        Boolean = { link = "Special" },
        NormalFloat  = { link = "Pmenu" },
    }
})
```
