### ISSUE TITLE
Can't override SpellBad highlight group

### ISSUE THREAD

**Issue by TxHawks** [rebelot/kanagawa.nvim#152]
I want spelling errors to be a little less conspicuous, so tried doing this, but spelling mistakes are still marked with a red undercurl:

```lua
overrides = function(colors)
  return {
    SpellBad = { undercurl = true, underline = false, sp = colors.palette.oldWhite },
  }
end
```

**Comment by rebelot** [comment]
hmm can't reproduce. make sure that `:hi SpellBad` shows the expected values (white undercurl). If this fails then make sure you don't have stuff overriding it somewhere in your config. Else, if the highlight is properly set,  try the `:Inspect` to see what hlgroup is used to highlight spelling errors that you keep seeing as red. My guess is that
