### ISSUE TITLE
Missing colors for markdown checklist's checked entries

### ISSUE THREAD

**Issue by evccyr** [rebelot/kanagawa.nvim#159]
Many of the entries in my todo list are actually checked. They don't appear to be checked with this colorscheme.
![image](https://github.com/rebelot/kanagawa.nvim/assets/85027668/94a40acd-0260-4339-80c3-12ea100259a1)

Big fan of your colorscheme :heart:

**Comment by marcelarie** [comment]
In `- [ ]` I get good coloring. 
<img width="1115" alt="Screenshot 2023-09-13 at 12 54 25" src="https://github.com/rebelot/kanagawa.nvim/assets/62728887/0230afa1-ce53-4a49-8dc8-f1a6e76ce210">
