### ISSUE TITLE
Transparency of some fields

### ISSUE THREAD

**Issue by andriati-alex** [rebelot/kanagawa.nvim#16]
I would like to know if it is possible to make some additional parts transparent, such as the command line and the diagnostic sign column. I just think is more consistent if these two fields can be transparent. I am attaching an image to illustrate the current behavior I would like to change.
Very nice theme by the way.

![Screenshot_20211229_195150](https://user-images.githubusercontent.com/14274511/147709185-adf623e0-7b2f-491a-abb1-2c896e32ee1a.png)
.

**Comment by rebelot** [comment]
please let me know if that's ok now.

**Comment by smjonas** [comment]
Related, could you make the `FloatBorder` background transparent as well? I think it looks better. Compare:

**Before:**
![floatborder_before](https://user-images.githubusercontent.com/40792180/147762167-268b6c26-3d59-49f5-a0ee-d147cdda0092.png)
**After:**
![floatborder_after](https://user-images.githubusercontent.com/40792180/147762177-f249cf71-9e65-4195-994b-9fd31140aa79.png)

Let me know what you think :)

**Comment by andriati-alex** [comment]
> please let me know if that's ok now.

yeah, thanks, now the sign column is transparent, but could you do the vim's command line transparent as well? (see just below my lualine in the screen image)

**Comment by rebelot** [comment]
> Related, could you make the `FloatBorder` background transparent as well? I think it looks better. Compare:
@smjonas `FloatBorder` bg should be set to NONE by default

**Comment by smjonas** [comment]
Ok thank you, then I am not sure which other plugin sets `FloatBorder` because it is only transparent if I set it explicitly

**Comment by rebelot** [comment]
> Ok thank you, then I am not sure which other plugin sets `FloatBorder` because it is only transparent if I set it explicitly

you could try inspect it with `:verbose hi FloatBorder`. Also you can try reloading the colorscheme with `:colo kanagawa` and check if the highlight is ok, if that does not work you can try listing colorscheme autocommands that may be set from other plugins with `:au ColorScheme` and `:au ColorschemePre`
