### ISSUE TITLE
need nvim config 

### ISSUE THREAD

**Issue by t-aswath** [rebelot/kanagawa.nvim#160]
this is not a issues , can i get the config files for the following nvim setup pls 
![image](https://github.com/rebelot/kanagawa.nvim/assets/119417646/08a44e08-9ec6-446c-8ca9-3914e8d2aa38)

**Comment by WieeRd** [comment]
The author's Neovim config files are in here <https://github.com/rebelot/dotfiles/tree/master/nvim>

**Comment by t-aswath** [comment]
thank you very much :smile:
