### ISSUE TITLE
Configuring Various Themes in kickstart.nvim Using rebelot/kanagawa.nvim

### ISSUE THREAD

**Issue by Barnoux** [rebelot/kanagawa.nvim#163]
**Description**
I am currently facing an issue while trying to configure different themes within the kickstart.nvim project using the rebelot/kanagawa.nvim plugin. I am seeking assistance in resolving this matter.

**Problem**
I have started my journey with nvim and opted to begin by setting up the kickstart.nvim project. To switch between themes, the kickstart project utilizes the lazy.nvim plugin. I initially tried using the "axiom" theme along with the themes from kanagawa, but I am only able to get the light mode to work.

**Specific Issue**
The main problem I'm encountering is that I cannot seem to get other themes, such as "dragon," to function as expected. Despite following the configuration provided below, I am unable to apply the desired themes:
```lua
{
    -- Kanagawa Theme
    "rebelot/kanagawa.nvim",
    priority = 1000,
    config = function()
      vim.cmd("colorscheme kanagawa-dragon")
    end,
  }
```
![Capture d’écran du 2023-08-25 11-12-27](https://github.com/rebelot/kanagawa.nvim/assets/47791676/e94bc577-d634-411f-a311-1e9b9b9ba705)

**Request for Assistance**
I am reaching out to the community for guidance and support. Could you kindly review my configuration and let me know if I'm missing any crucial steps? Your expertise would be invaluable in helping me overcome this roadblock.

Did i Read correctly The Friendly Manuel  ?

Thank you in advance for your time and assistance.

Best regards,

BBA

**Comment by pooseethestroyer** [comment]
Set the bg option to dark
`:set bg=dark`

And see if it works, if so
`vim.o.bg="dark"`
Will work when you past in your config

If it doesn't work try
`:KanagawaCompile`

**Comment by Barnoux** [comment]
Thank you :+1:  @pooseethestroyer it's working !

**Comment by pmatulis** [comment]
But *why* is it working?
