### ISSUE TITLE
Different bg color for inactive window

### ISSUE THREAD

**Issue by kuntau** [rebelot/kanagawa.nvim#17]
Can we have some option like [nightfox](https://github.com/EdenEast/nightfox.nvim#%EF%B8%8F-configuration) to _dim_ inactive window. This will help if we have many window/split open.

`help NormalNC`

**Comment by rebelot** [comment]
Would you be happy with something like this?

```lua
require'kanagawa'.setup({
    overrides  = {
        NormalNC = { link = 'StatusLine' },
    }
})
```

**Comment by kuntau** [comment]
> Would you be happy with something like this?
> 
> ```lua
> require'kanagawa'.setup({
>     overrides  = {
>         NormalNC = { link = 'StatusLine' },
>         -- or try this one
>         -- NormalNC = { bg = '#181820' },
>     }
> })
> ```

What does `link = 'StatusLine'` mean? Using color same as `status line`?

**Comment by rebelot** [comment]
Yes, link means that the inactive window will have the same background and foreground colors of the statusline. You can experiment with other palette colors to see what you like. The other proposed color is not part of the palette at the moment but I can add it as `sumiInk1b` -> `bg_dim` for this specific purpose.

**Comment by kuntau** [comment]
Second option look good to me 💯

**Comment by LudoPinelli** [comment]
@kuntau As an alternative, you could also consider using [shade](https://github.com/sunjon/Shade.nvim ) wich dim inactive windows, it's pretty nice.

**Comment by rebelot** [comment]
feature added in 6b2b37466c9702700aa47a364711222ddfabf6aa
