### ISSUE TITLE
Colors for Diffview Not Applied

### ISSUE THREAD

**Issue by harrisoncramer** [rebelot/kanagawa.nvim#19]
Hello! Thank you for the great color scheme.

I'm using <a href="https://github.com/sindrets/diffview.nvim">diffview</a> to view changes in a file, and noticed that the way the colorscheme is currently configured, those changes are colored as grey and light grey, rather than the colors provided.

This is not ideal, I'd love it to be the traditional red as deleted, green as added, and so forth. Those colors are provided inside the `themes.lua` file, do they need to be applied somehow? How could one debug this?

<img width="1381" alt="Screen Shot 2022-01-01 at 9 50 04 PM" src="https://user-images.githubusercontent.com/32515581/147864747-214f969d-b557-4118-af60-39e1649d1bd3.png">

Thanks again!

**Comment by rebelot** [comment]
uhm, it works as expected for me. make sure that kanagawa is loaded before diffview!

**Comment by harrisoncramer** [comment]
I've specified the "after" keyword using packer, perhaps this is a bug in their repository. Here are my <a href="https://github.com/harrisoncramer/nvim/tree/main">dotfiles</a> for reference, I'm not sure what's happening!

**Comment by rebelot** [comment]
I had similar problems when managing colorschemes using packer config. For the sake of simplicity, you can add kanagawa configuration, setup and require the colorscheme directly in your init.lua (or in any file that is sourced/required explicitly from that)

**Comment by harrisoncramer** [comment]
Yes, thank you that worked! I've just loaded it before any of the other plugins manually.
