### ISSUE TITLE
Embarrassing question on setting highlight in `setup()`-call

### ISSUE THREAD

**Issue by PhilippFeO** [rebelot/kanagawa.nvim#193]
I use preservim/vim-markdown and have the following code in my `ftplugin/markdown.lua` file:
```lua
local colors = require("kanagawa.colors").setup()
local cp = colors.palette
local highlight = vim.api.nvim_set_hl

highlight(0, "htmlBold", { fg = cp.autumnRed, bold = true })
```
This works as expected.

When I use the followin line in the `setup()`-call
```lua
    overrides = function(colors)
        local theme = colors.theme
        return {
            htmlBold = { fg = theme.autumnRed, bold = true },
        ...
        }
    end
}
```
the highlight doesn't apply. I haven't found any hints on where to set my own highlights except in the `overrides` section. The highlight of other highlight groups, fi. the `Telescope.*` ones from your examples works well. What am I doing wrong?

**Comment by rebelot** [comment]
`autumnRed` is a palette color, not a theme color
