### ISSUE TITLE
Upcoming changes to treesitter highlight captures

### ISSUE THREAD

**Issue by alex-tdrn** [rebelot/kanagawa.nvim#197]
This is not really actionable yet, but posting this early for anyone using nightly `neovim` and master `nvim-treesitter`.

The tree-sitter highlight captures have been changed to align with upstream tree-sitter and helix captures on [nvim-treesitter master](https://github.com/nvim-treesitter/nvim-treesitter/pull/5895). [Release v0.9.2](https://github.com/nvim-treesitter/nvim-treesitter/releases/tag/v0.9.2)  is apparently the last one using the old captures. 

Neovim bundled parsers [will also use these captures for version 10](https://github.com/neovim/neovim/pull/27067) (although nightly users will be affected sooner, of course). Once these captures land into stable neovim, kanagawa will need to update its treesitter highlights.

Until then, I've taken the time to find out what needs updating and link the old captures to the new ones. This way, both new and old highlight queries will work, and users can simply copy-paste this override into their configs until things stabilize and the new captures are used throughout the ecosystem.
If you're here and noticed that highlighting does not look the same with latest nvim-treesitter master, just add the following to your overrides( do not forget `:KanagawaCompile`):
```lua
require("kanagawa").setup({
    overrides = function(colors)
        return {
            -- update kanagawa to handle new treesitter highlight captures
            ["@string.regexp"] = { link = "@string.regex" },
            ["@variable.parameter"] = { link = "@parameter" },
            ["@exception"] = { link = "@exception" },
            ["@string.special.symbol"] = { link = "@symbol" },
            ["@markup.strong"] = { link = "@text.strong" },
            ["@markup.italic"] = { link = "@text.emphasis" },
            ["@markup.heading"] = { link = "@text.title" },
            ["@markup.raw"] = { link = "@text.literal" },
            ["@markup.quote"] = { link = "@text.quote" },
            ["@markup.math"] = { link = "@text.math" },
            ["@markup.environment"] = { link = "@text.environment" },
            ["@markup.environment.name"] = { link = "@text.environment.name" },
            ["@markup.link.url"] = { link = "Special" },
            ["@markup.link.label"] = { link = "Identifier" },
            ["@comment.note"] = { link = "@text.note" },
            ["@comment.warning"] = { link = "@text.warning" },
            ["@comment.danger"] = { link = "@text.danger" },
            ["@diff.plus"] = { link = "@text.diff.add" },
            ["@diff.minus"] = { link = "@text.diff.delete" },
        }
    end,
})
```

Thank you for all the time and hard work put into this amazing colorscheme, nothing really comes close to it for me  (also, heirline is awesome as well 😛).

**Comment by kohane27** [comment]
You're a life-saver. Thank you!

**Comment by JeremyChuaWX** [comment]
I think the capture for TODO comments were missed.

```lua
require("kanagawa").setup({
    overrides = function(colors)
        return {
            -- ...
            ["@comment.todo"] = { link = "@text.todo" },
            -- ...
        }
    end,
})
```

**Comment by alex-tdrn** [comment]
I've removed the overrides in my config and am happy with how things look after https://github.com/rebelot/kanagawa.nvim/commit/75be2b90c135a6cdacf05826aeb44dcf0c95df3c (at least in c++, rust, markdown, and lua)
