### ISSUE TITLE
How to change color and style of text under cursor

### ISSUE THREAD

**Issue by sheldonlyr** [rebelot/kanagawa.nvim#200]
I want to change color and style(disable underline) of text under cursor, but can not find how, please help!
<img width="983" alt="Screen Shot 2024-01-31 at 17 53 49" src="https://github.com/rebelot/kanagawa.nvim/assets/17898112/43438c94-12c3-46ff-8d7d-681da9babf2c">

**Comment by TinusgragLin** [comment]
If I understand you correctly, you want to get rid of the underlines that appears under all the "output"s in the screen shot, is that correct?

In that case, it's very likely that you have installed some plugin that underlines the word under the cursor to help you see the usages of a variable under the cursor and you should check the relevant options that plugin offers.

**Comment by sheldonlyr** [comment]
> If I understand you correctly, you want to get rid of the underlines that appears under all the "output"s in the screenshot, is that correct?

@TinusgragLin  Thanks for your reply！You are right, that is my intention and I have already solved this issue.
I'm using lazyvim and vim-illuminate plugin, below is my config of kanagawa:

```
{
    "rebelot/kanagawa.nvim",
    opts = function()
      return {
        undercurl = false,
        commentStyle = { italic = false },
        keywordStyle = { italic = false },
        statementStyle = { italic = false, bold = false },
        transparent = false,
        dimInactive = false,
        terminalColors = true,

        overrides = function(colors)
          return {
            IlluminatedWordText = { link = "DiffText" },
            IlluminatedWordRead = { link = "DiffText" },
            IlluminatedWordWrite = { link = "DiffText", underline = true },
          }
        end,
      }
    end,
},
```

**Comment by TinusgragLin** [comment]
> > If I understand you correctly, you want to get rid of the underlines that appears under all the "output"s in the screenshot, is that correct?
> 
> @TinusgragLin Thanks for your reply！You are right, that is my intention and I have already solved this issue. I'm using lazyvim and vim-illuminate plugin, below is my config of kanagawa:
> 
> ```
> {
>     "rebelot/kanagawa.nvim",
>     opts = function()
>       return {
>         undercurl = false,
>         commentStyle = { italic = false },
>         keywordStyle = { italic = false },
>         statementStyle = { italic = false, bold = false },
>         transparent = false,
>         dimInactive = false,
>         terminalColors = true,
> 
>         overrides = function(colors)
>           return {
>             IlluminatedWordText = { link = "DiffText" },
>             IlluminatedWordRead = { link = "DiffText" },
>             IlluminatedWordWrite = { link = "DiffText", underline = true },
>           }
>         end,
>       }
>     end,
> },
> ```

Wow, a big thank for mentioning vim-illuminate! I used to have a similar plugin installed for my vim setup, then after switching to neovim I never managed to remember the name of that plugin. Now I think I have just found it!

**Comment by TinusgragLin** [comment]
So I think this should be closed? @sheldonlyr

**Comment by sheldonlyr** [comment]
Yes, i will close this issue
