### ISSUE TITLE
markdown highlighting is no longer working

### ISSUE THREAD

**Issue by ctranstrum** [rebelot/kanagawa.nvim#202]
Looks like there was a recent change to treesitter that needs some adjustments to the colorscheme to get markdown highlighting working again.

Issue in the markdown parser, closed with a note to update the colorscheme: https://github.com/MDeiml/tree-sitter-markdown/issues/131

Note about the treesitter breaking change, with a note to update the colorscheme: https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583

New(?) format for highlighting groups: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights

Commit message for the breaking change, noting the group changes: https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0

**Comment by MikeWelsh801** [comment]
Thanks for posting those links! I updated the tags and submitted a PR #203, and it seems to work for me now.

**Comment by ctranstrum** [comment]
Oh, and now I see that the workaround is already posted in #197.

**Comment by MikeWelsh801** [comment]
Ah, I see. I just forked and basically changed the same captures in the treesitter.lua file. I can understand why they might not want to totally update it yet if treesitter is still changing stuff.

**Comment by jackfranklin** [comment]
For what it's worth, on the latest release, this is now resolved for me. Thanks!
