### ISSUE TITLE
Background color issues with plugins like Noice

### ISSUE THREAD

**Issue by SpacewaIker** [rebelot/kanagawa.nvim#204]
I don't know much about neovim theming so maybe this is very simple to fix, but I'm having issues with the background coloring in some fancier UI elements. For instance:
<img width="1082" alt="image" src="https://github.com/rebelot/kanagawa.nvim/assets/63059540/71b5c775-d92f-4844-96bd-a98a776accaa">

Compared to catpuccin:
<img width="1113" alt="image" src="https://github.com/rebelot/kanagawa.nvim/assets/63059540/a0cc73ec-055d-4ed0-a18a-796d00491291">

What I consider "wrong" in the above is the color of the line number column being different than the normal background, the color of the context (nvim-treesitter-context), and the noice.nvim window looking weird. Things like telescope seem to work well so I'm wondering how I could fix this?

Thanks!

**Comment by yifan0414** [comment]
you mean this?

Common customizations
Remove gutter background
Remove the background of LineNr, {Sign,Fold}Column and friends

```
colors = {
    theme = {
        all = {
            ui = {
                bg_gutter = "none"
            }
        }
    }
}
```

**Comment by SpacewaIker** [comment]
Hmmmm yes... I probably should've checked the readme fully before opening an issue, I just didn't know that themes could be configured like other plugins. 

My bad! Sorry about this
