### ISSUE TITLE
Match VSCode Markdown Colorscheme

### ISSUE THREAD

**Issue by Tainted-Fool** [rebelot/kanagawa.nvim#207]
The colorscheme [kanagawa](https://marketplace.visualstudio.com/items?itemName=qufiwefefwoyn.kanagawa) in vscode has a completely different colors compared to the nvim version. How can I make it look like this?

fyi, I had to enable this override in issue [#197](https://github.com/rebelot/kanagawa.nvim/issues/197) because markdown syntax is not working for me with latest commit `ab41956`

Here is what the markdown colorscheme looks like in vscode
![image](https://github.com/rebelot/kanagawa.nvim/assets/19850526/0d190540-f705-4756-9091-18dcb8a2a035)

Here is what the markdown colorscheme looks like in nvim
![image](https://github.com/rebelot/kanagawa.nvim/assets/19850526/3c653b87-56cc-4e5b-a0e3-dfad33a016f9)

How can I get the colors to look like the vscode version?

**Comment by Tainted-Fool** [comment]
I figured it out. I had to add this to change the default colors. I couldn't change color on `Google` but maybe that's a token or something?

```lua
            ["@markup.link.url.markdown_inline"] = { link = "Special" }, -- (url)
            ["@markup.link.label.markdown_inline"] = { link = "WarningMsg" }, -- [label]
            ["@markup.italic.markdown_inline"] = { link = "Exception" }, -- *italic*
            ["@markup.raw.markdown_inline"] = { link = "String" }, -- `code`
            ["@markup.list.markdown"] = { link = "Function" }, -- + list
            ["@markup.quote.markdown"] = { link = "Error" }, -- > blockcode
```

![image](https://github.com/rebelot/kanagawa.nvim/assets/19850526/c68d125b-8a5c-4c16-b44a-d9c8fc9f5201)

**Comment by gary-norman** [comment]
Thanks :)
