### ISSUE TITLE
Show End of Buffer signs

### ISSUE THREAD

**Issue by primeapple** [rebelot/kanagawa.nvim#214]
Hi, I have a tiny issue.

I want to show the `~` tilde signs that represent the end of a buffer. I thought I could add the following to my overrides:

```
                        EndOfBuffer = { fg = theme.ui.fg, bg = theme.ui.bg_gutter },
                        NonText = { fg = theme.ui.fg, bg = theme.ui.bg_gutter },
```
But sadly that doesn't do anything. Does anyone now what to set? Catpucccin did it in this commit https://github.com/catppuccin/nvim/commit/ca99c89638e63fe123a6c31190b546887e82d0ca

**Comment by rebelot** [comment]
I can't reproduce your issue, the above overrides should work as expected.
1) did you enable compilation? If so, remember to use the `:KanagawaCompile` command
2) check if other plugins (possibly colorschemes?) are overriding your config
