### ISSUE TITLE
Which-key italics

### ISSUE THREAD

**Issue by Caddy121** [rebelot/kanagawa.nvim#219]
How can I keep italics enabled but only disabled in the which-key menu?

**Comment by terje** [comment]
You can override specific highlight groups as part of the theme setup. Here's an example for setting regular - non italic - text for the which key groups:

```lua
overrides = function(colors)
  local theme = colors.theme
  return {
    WhichKeyGroup = { fg = theme.ui.special, italic = false },
  }
end,
```

**Comment by Caddy121** [comment]
Awesome, thank you!
