### ISSUE TITLE
how to get color palette ?

### ISSUE THREAD

**Issue by nekonako** [rebelot/kanagawa.nvim#23]
previously i use something like this `local colors = require("kanagawa.colors")` to get the color palette table.
And i can use like this `colors.oniViolet` to get specific color, previously no this is problem, but after updating the plugin i always get the null.

how i get color palette for latest version ?

btw i really like this colorscheme.
i'm sorry for my english.
cheers...(UwU)

**Comment by nekonako** [comment]
i make pull request for this issue

https://github.com/rebelot/kanagawa.nvim/pull/24

**Comment by rebelot** [comment]
You can see the readme. You can access colors like this:
```lua
local colors = require'kanagawa.colors'.setup()
```
