### ISSUE TITLE
Updating to nvim 0.10.0 breaks certain highlight groups

### ISSUE THREAD

**Issue by evanrittenhouse** [rebelot/kanagawa.nvim#242]
I upgraded from Neovim 0.9.4 to Neovim 0.10.0, Kanagawa commits bfa818c7bf6259152f1d89cf9fbfba3554c93695 to bfa818c7bf6259152f1d89cf9fbfba3554c93695. Certain Rust highlight groups are now broken:
<img width="781" alt="Screenshot 2024-06-09 at 9 43 53 AM" src="https://github.com/rebelot/kanagawa.nvim/assets/84083822/6ad99b43-678f-493e-8628-287b5c83a355">

For example, macros used to be red (similar to `self`'s coloring), and fully qualified `impl` paths were white. Did anything change in Treesitter or something to mess with the colors? I don't really keep up with the ecosystem at all. Pinning the commit hash to `bfa818` still has the error, so I'm guessing Treesitter queries may have changed?

Not even really sure if this is an issue for this repo or not, but I'm wondering if anyone else has seen colors change after an update unexpectedly.

**Comment by Rattko** [comment]
I've seen the same problem with highlighting in general. I've had to temporarily switch to other colorschemes cause it has made my experience with Python and shell scripting really unpleasant. Hope this gets resolved quickly.

**Comment by rebelot** [comment]
That could be due to semantic highlights provided by lsp. Use the `:Inspect` command on highlights that seem off and provide detailed suggestions on what groups you don't like

**Comment by evanrittenhouse** [comment]
On a macro:
```
Treesitter
  - @variable.rust links to @variable rust
  - @function.macro.rust links to Function rust

Semantic Tokens
  - @lsp.type.macro.rust links to Constant priority: 125
  - @lsp.mod.defaultLibrary.rust links to @lsp priority: 126
  - @lsp.mod.library.rust links to @lsp priority: 126
  - @lsp.typemod.macro.defaultLibrary.rust links to @lsp priority: 127
  - @lsp.typemod.macro.library.rust links to @lsp priority: 127
```

On one of the fully qualified paths:
```
Treesitter
  - @variable.rust links to @variable rust
  - @module.rust links to Type rust

Semantic Tokens
  - @lsp.type.namespace.rust links to Type priority: 125
  - @lsp.mod.crateRoot.rust links to @lsp priority: 126
  - @lsp.mod.defaultLibrary.rust links to @lsp priority: 126
  - @lsp.mod.library.rust links to @lsp priority: 126
  - @lsp.typemod.namespace.crateRoot.rust links to @lsp priority: 127
  - @lsp.typemod.namespace.defaultLibrary.rust links to @lsp priority: 127
  - @lsp.typemod.namespace.library.rust links to @lsp priority: 127
```

**Comment by evanrittenhouse** [comment]
I figured out the namespace issue. Consider `name::space::Enum`. `name` and `space` both resolve to `lsp.type.namespace.rust`, which resolves to a `Type`:
```
  - @lsp.type.namespace.rust links to Type priority: 125
```
Previously, I don't think this was the case.

Additionally, `decorators.rust` now resolve to constants, similar to `macro.rust`s. I'm not sure if you plan on changing these or anything, but if you do, hope the additional info helps

**Comment by AreamanM** [comment]
I upgraded to the latest Kanagawa version and verified that the change in 54e7382 is reflected in highlights/lsp.lua on my machine. Despite that, with C++/clangd, @lsp.type.macro links to @constant.macro. I don't mind the macros being orange but I am just curious about why that could happen in the first place.
