### ISSUE TITLE
QUESTION: how to get the folding in the screenshot

### ISSUE THREAD

**Issue by dbatten5** [rebelot/kanagawa.nvim#244]
How do you get the sticky class name / function name as shown in the screenshot? 
<img width="772" alt="image" src="https://github.com/rebelot/kanagawa.nvim/assets/17271241/61850d69-6fef-479d-8b58-8b12bd5c3aae">
Is that done through a plugin?

**Comment by aliaksandr-trush** [comment]
I believe it's https://github.com/nvim-treesitter/nvim-treesitter-context

**Comment by nohehf** [comment]
Re opening this, is there somewhere we can find the nvim config shown in the screenshots ? It looks great !
