### ISSUE TITLE
Too much fujiWhite everywhere

### ISSUE THREAD

**Issue by robbyki** [rebelot/kanagawa.nvim#32]
Really love these colors but just trying to figure out why I am getting way too much `fujiWhite` everywhere in my code and the easiest way to make it render more colors based on the built-ins for scala but also applies to all of my java files. Using basic config as follows:

```
⋅⋅⋅⋅⋅⋅⋅⋅use({
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅"rebelot/kanagawa.nvim",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅config⋅=⋅function()↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅require("kanagawa").setup({↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅undercurl⋅=⋅true,⋅--⋅enable⋅undercurls↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅commentStyle⋅=⋅"italic",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅functionStyle⋅=⋅"NONE",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅keywordStyle⋅=⋅"italic",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅statementStyle⋅=⋅"bold",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅typeStyle⋅=⋅"NONE",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅variablebuiltinStyle⋅=⋅"italic",↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅specialReturn⋅=⋅true,⋅--⋅special⋅highlight⋅for⋅the⋅return⋅keyword↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅specialException⋅=⋅true,⋅--⋅special⋅highlight⋅for⋅exception⋅handling⋅keywords↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅transparent⋅=⋅false,⋅--⋅do⋅not⋅set⋅background⋅color↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅dimInactive⋅=⋅true,⋅--⋅dim⋅inactive⋅regions↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅colors⋅=⋅{},↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅overrides⋅=⋅{},↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅})↴
  ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅end,↴
  ⋅⋅⋅⋅⋅⋅⋅⋅})
```

![image](https://user-images.githubusercontent.com/1027357/151779812-45c63426-fe28-4e44-8e36-83c3fc6de76b.png)

**Comment by rebelot** [comment]
This is very strange. I don't think the issue is related to kanagawa. It looks more like the syntax parser had a mini-stroke. Are you using treesitter? if so, try enabling/disabling it to see what happens. you could also try reloading the buffer.

**Comment by robbyki** [comment]
you're right sorry about that. not Kanagawa. thanks for the pointer. works fine when I open it directly from telescope: 
![image](https://user-images.githubusercontent.com/1027357/151783590-021024f6-8e43-40a9-91f3-bc243daca45d.png)
