### ISSUE TITLE
Cloned theme for Emacs

### ISSUE THREAD

**Issue by konrad1977** [rebelot/kanagawa.nvim#34]
Hi there. I saw your theme, loved it but I am an Emacs user so I cloned it.
I will upload it to Melpa (Emacs packages)

https://github.com/konrad1977/emacs/blob/main/themes/kanagawa-theme.el

Do you have any copyright etc you want me to include?

Btw here is a screenshot
<img width="2172" alt="Skärmavbild 2022-02-07 kl  13 04 07" src="https://user-images.githubusercontent.com/4384932/152784825-918fa346-94b7-49b4-9600-e1ab70f89345.png">

//Mikael

**Comment by rebelot** [comment]
Great-looking port! nice work! You can do whatever you like with the theme, however a couple of things I'd appreciate:

1) mention original artist 
>  inspired by the colors of the famous painting by Katsushika Hokusai
2) maybe include a link to this repo or just mention `rebelot` somewhere!

thanks :)

**Comment by rebelot** [comment]
Thanks!
