### ISSUE TITLE
Add support for split borders 

### ISSUE THREAD

**Issue by ihasdapie** [rebelot/kanagawa.nvim#38]
With https://github.com/neovim/neovim/pull/17266 being merged in it would be nice to have better highlights and drawing characters for splits. 

This is what kanagawa looks like right now
![image](https://user-images.githubusercontent.com/54821716/159060160-bfddfcd4-7fd9-47db-a0af-97fba07ed1a6.png)

As opposed to another colorscheme which implements it e.g. gruvbox or catppuccin
![image](https://user-images.githubusercontent.com/54821716/159060367-27465cd5-b638-4377-9761-533d1fd45879.png)

**Comment by rebelot** [comment]
Yup, I was playing with this today. I will add a `globalStatus` bool option to control the highlighting of window separator. I'll see wether  it's best to also add fillchars presets or not.

**Comment by rebelot** [comment]
it's now supported as of 42584e5

**Comment by kting28** [comment]
Hi I'm looking at enabling the split border but this `globalStatus` option is no longer there. What's the latest way of making the split separator more visible?

**Comment by rebelot** [comment]
You can use thicker `'fillchars'`, or change their color to your liking, e.g.
```lua
            require("kanagawa").setup({
                overrides = function(colors)
                    local theme = colors.theme
                    return {
                        WinSeparator = { fg = theme.ui.nontext }, -- brighter
                        WinSeparator = { fg = "black" }, -- darker
                    }
                end,
            })
```

**Comment by kting28** [comment]
Awesome thanks! Just another question - this changes the color of the active win separator. How about the inactive one? (i.e. in horizontal split when the lower is active and upper bar is inactive). Want to see where to override to make that lighter. Thanks.

**Comment by rebelot** [comment]
> Awesome thanks! Just another question - this changes the color of the active win separator. How about the inactive one? (i.e. in horizontal split when the lower is active and upper bar is inactive). Want to see where to override to make that lighter. Thanks.

there's no such hlgroup. The closest thing to that would be using `dimInactive`,
This is the default value for `WinSeparator` taking `dimInactive` option into account
```lua
        WinSeparator = { fg = theme.ui.bg_m3, bg = config.dimInactive and theme.ui.bg_dim or "NONE" },
```

**Comment by kting28** [comment]
For me it seems `dimInactive` is flipped as in the dimmed split actually got highlighted due to the higher contrast (the bg got darker while text is the same ). Will mess around to see if I can flip it.
