### ISSUE TITLE
tmux colors?

### ISSUE THREAD

**Issue by casperstorm** [rebelot/kanagawa.nvim#40]
First of all, thank you so much for this beautiful theme. It is funny when i am picking a scheme; i never really know what im looking for but i just KNOW when i've found the one.

I couldn't help notice you also had a tmux theme which fitted nicely together with kanagawa, if you have time at some point i would love to use it as well.

**Comment by rebelot** [comment]
thanks! you can see my `tmux.conf` in https://github.com/rebelot/dotfiles. Tmux will just pick terminal colors 0 to 15 when using default names like `black`, `white`, `red`, `green`, `yellow`, `blue`, `cyan`, `magenta` and their `bright*` alternatives. So you only need to add kanagawa colors to your terminal.
