### ISSUE TITLE
vim-plug support to download this theme

### ISSUE THREAD

**Issue by ciscohack** [rebelot/kanagawa.nvim#43]
Hello expert,

Can you please add the vim-plug plugin support to download this theme. Thanks

**Comment by Kypert** [comment]
If you refer to https://github.com/junegunn/vim-plug then I believe there is nothing special that you need to do, simply add this between the `plug#begin` and `plug#end` sections:

`Plug 'rebelot/kanagawa.nvim'`

Please clarify if you mean something else :)

**Comment by ciscohack** [comment]
@Kypert I have tried this setting only but it was throwing error for me and was not able to download the theme so i raise a request

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/11479557/159682763-63af73a3-52e2-4fc2-8eee-36d9116496e0.png">

**Comment by rebelot** [comment]
@ciscohack I'm sorry but I don't see how this issue could be related to kanagawa.nvim. Plugins do not need to specify any kind of support for plugin managers. You can use any plugin manager you like (or none at all) to download and install this colorscheme.

Read your errors carefully and fix your configuration. From your screenshot I can see the first error is related to which_key.

**Comment by ciscohack** [comment]
@rebelot Thanks my friend i have rechecked my config and noticed i put config mistake.. instead of writing Plug i wrote small p (plug) that was causing all this error. Thanks guys for supporting
