### ISSUE TITLE
Override NvimTree background color

### ISSUE THREAD

**Issue by gmr458** [rebelot/kanagawa.nvim#44]
the color changes when I change the cursor position from NvimTree to the editor and the top of the NvimTree does not change color
<video src="https://user-images.githubusercontent.com/53343401/162065562-e7ed2ca5-6034-4bf7-a3b8-3e6c72ebbf4f.mp4" width="100%"></video>

I am trying to get something like this:
![screenshot](https://raw.githubusercontent.com/gmr458/nvim/main/screenshots/screenshot1.png)

**Comment by rebelot** [comment]
this should do ;)
```lua
local overrides = {
    NvimTreeNormal = { bg = 'red' },
    NvimTreeNormalNC = { link = 'NvimTreeNormal' }
}

```

**Comment by gmr458** [comment]
@rebelot Thanks.
