### ISSUE TITLE
Returns `palette_colors` from kanagwa.colors.setup()

### ISSUE THREAD

**Issue by fitrh** [rebelot/kanagawa.nvim#45]
Thanks for the beautiful scheme.

Recently I tried to override and set some highlight groups based on this theme colors palette, and found that I couldn't
get proper code completion from the lua LSP (which sometimes caused misspelling as I has to write them manually), 
apparently the cause was since the `kanagawa.colors` module returns table from `vim.tbl_extend`, not the actual 
palette table, my workaround for this is to assign the final result to `palette_colors`.

> Previously, the completion came from what I wrote for the `c` variable, although it is unrelated
![20220407_203340_full](https://user-images.githubusercontent.com/55179750/162204423-cb0062fe-466e-4b94-9d1e-c010d3f8cd2d.jpg)

> After, completion came from the actual `palette_colors`
![20220407_203438_full](https://user-images.githubusercontent.com/55179750/162204948-94b7fe4d-b9be-48d0-8918-d9363ce544b0.jpg)

```diff
diff --git a/lua/kanagawa/colors.lua b/lua/kanagawa/colors.lua
index baf2fde..9facef9 100644
--- a/lua/kanagawa/colors.lua
+++ b/lua/kanagawa/colors.lua
@@ -67,7 +67,8 @@ function M.setup(config)
     local colors = vim.tbl_extend("force", palette_colors, config.colors)
     local theme = require("kanagawa.themes")[config.theme](colors)
     theme = vim.tbl_extend("force", theme, config.colors)
-    return vim.tbl_extend("force", theme, colors)
+    palette_colors = vim.tbl_extend("force", theme, colors)
+    return palette_colors
 end
 
 return M
```

Sure, this has nothing to do with the color scheme, but it's a good DX.

**Comment by rebelot** [comment]
the problem with this is that it may change the original `palette_colors`. Also it may be misleading, as the output from `kanagawa.colors.setup()` is the merged table of `palette_colors` and `theme`, but only the former show a nice LSP completion. I am not sure how many would notice, but modifying the original colors invalidates the whole config design

**Comment by fitrh** [comment]
Yes, and I think this is due to lua's limitations as an *untyped* language
