### ISSUE TITLE
All variables get dyed red when array(C/C++) is missing index and its line of code the semicolon

### ISSUE THREAD

**Issue by EmKian** [rebelot/kanagawa.nvim#46]
So, I've been trying out this colorscheme for a few days now(I absolutely love it btw) and I have stumbled upon this really obtrusive behavior of coloring every single variable red whenever I type in an array the way shown in the image appended. Curiously, it all goes away as soon as I end the line with a semicolon.
![image](https://user-images.githubusercontent.com/64203462/164186255-9789ac8d-7767-4d0a-a2a2-d9af8074d1f8.png)

**Comment by EmKian** [comment]
My bad, dug into the code a bit and found out it's not Kanagawa's fault and that TSError is the culprit of all this. Still I think its color should be changed, having your code constantly flash red while you're still typing isn't really fun

**Comment by rebelot** [comment]
I totally agree. I started to find it annoying myself. I will link it to normal by default

**Comment by EmKian** [comment]
Aight, I'll close the issue now that  you're fixed that
