### ISSUE TITLE
In python: the comment out codes have the same color !! 

### ISSUE THREAD

**Issue by sabirdvd** [rebelot/kanagawa.nvim#47]
Hi, thank you for making this great theme. In python, the comment codes have the same color as the uncomment ones (comment out), which makes it difficult to read/write note above python code. I'm using the last version of neovim.  
![kanagawa](https://user-images.githubusercontent.com/18333226/171996921-4ba111fe-320d-4905-a2ca-e23858335a3b.jpg)

**Comment by rebelot** [comment]
Based on your screenshot you're not seeing the colorscheme as it should be. Like at all.

**Comment by sabirdvd** [comment]
Thank you for the fast response, I had problems with only python, with LaTex and HTML work perfectly. As you said maybe there was a conflict between different plugins  so I re-installed everything from scratch and cleaned themes.vim and enable treesitter highlighting, now everything works like a charm. Again thanks for your help and for making this great theme.
