### ISSUE TITLE
Table of color pallete

### ISSUE THREAD

**Issue by mnacamura** [rebelot/kanagawa.nvim#5]
Thanks for creating this nice colorscheme!

Would you mind by any chance adding a table of your color palette somewhere, probably to README? So that users can easily customize for example their statusline colors using kanagawa's palette.
The table would contain color names (`samuraiRed`, etc.), their corresponding HEX values, and actual color images, defined in `lua/kanagawa/colors.lua`. I imagine something like [this][1].

[1]: https://github.com/srcery-colors/srcery-vim#tui

**Comment by rebelot** [comment]
I am working on it. It is quite tedious as there are many colors and I have to generate single images for each of them, so it could take a while. For the moment, I can suggest you to open the source `colors.lua` and view it with the support of colorizing plugins, such as https://github.com/norcalli/nvim-colorizer.lua.

**Comment by rebelot** [comment]
done ;) 7118690e5a0415407d9d0438a128365a73837282

**Comment by mnacamura** [comment]
Perfect! Thanks!
