### ISSUE TITLE
Bold and italics don't work in newest commit

### ISSUE THREAD

**Issue by sanka047** [rebelot/kanagawa.nvim#50]
Italics and bold no longer work after the latest commit. I have already made the updates to my config (I'm on v0.7.0):
```
function M.setup()
    local ok, kanagawa = pcall(require, 'kanagawa')
    if not ok then
        log.error('kanagawa not available', 'Config')
        return false
    end

    vim.g.kanagawa_lualine_bold = true

    kanagawa.setup({
        undercurl = true,
        commentStyle = { italic = true },
        functionStyle = { bold = true },
        keywordStyle = { bold = true },
        statementStyle = { bold = true },
        typeStyle = { bold = true },
        variablebuiltinStyle = { bold = true },
        specialReturn = true,
        specialException = true,
        transparent = false,
        dimInactive = false, -- while shade is broken
        globalStatus = true,
        colors = {},
        overrides = {},
    })

    vim.cmd('colorscheme kanagawa')
end
```
Here's what it currently looks like:
<img width="1087" alt="Screen Shot 2022-06-10 at 9 58 11 PM" src="https://user-images.githubusercontent.com/50463858/173170073-037a280c-d920-433e-b8d3-8c99890a06e8.png">

Prior to the latest commit (I pinned [this commit](https://github.com/rebelot/kanagawa.nvim/commit/a6db77965a27ca893ea693d69cc3c152c000a627)):
<img width="1080" alt="Screen Shot 2022-06-10 at 10 00 06 PM" src="https://user-images.githubusercontent.com/50463858/173170163-6fe81fc4-dcda-4551-97ec-4c348665d5c2.png">

**Comment by sanka047** [comment]
I believe that `unpack` doesn't do exactly what we'd want [here](https://github.com/rebelot/kanagawa.nvim/pull/49/commits/dc51a2385068083f324b28649cb41c5a7290dfa2#diff-0b0e6aea227ac13f0ccd93a8d084a7a9704cb3febb18833754b71c32c13c4fe5R10).
```
> print(unpack({ bold = true, italic = true }))

```
It seems like `unpack` is only meant to work with lists from the [docs](http://www.lua.org/manual/5.1/manual.html#pdf-unpack)

**Comment by sanka047** [comment]
Working on a PR

**Comment by rebelot** [comment]
Thanks! sorry for the inconvenience, I took the code from a branch I thought I have tested but wasn't the case :)

**Comment by sanka047** [comment]
No worries 😛 

Unfortunately, `unpack` fails quietly on tables
