### ISSUE TITLE
Bufferline background changed after dc51a23

### ISSUE THREAD

**Issue by sseneca** [rebelot/kanagawa.nvim#52]
https://github.com/rebelot/kanagawa.nvim/commit/dc51a2385068083f324b28649cb41c5a7290dfa2 made the background of bufferline white for me, whereas previously it was black. Before and after below:

![2022-06-13T17:36:02,537462404+01:00](https://user-images.githubusercontent.com/25619071/173402141-07a0d382-c27d-42dd-84f4-55f2e7c5c9b2.png)

![2022-06-13T17:35:28,074178445+01:00](https://user-images.githubusercontent.com/25619071/173402143-d0bdcdee-4ae7-4026-a548-7c975f2e608c.png)

I don't have a big config for Kanagawa so idk what to change:

```lua
vim.opt.laststatus = 3
vim.opt.fillchars:append({
  horiz = '━',
  horizup = '┻',
  horizdown = '┳',
  vert = '┃',
  vertleft = '┨',
  vertright = '┣',
  verthoriz = '╋',
})
require('kanagawa').setup({ globalStatus = true, ... })
vim.cmd('colorscheme kanagawa')
```

**Comment by rebelot** [comment]
This happens to me with transparency enabled. If this does not solve it, you should override bufferline highlights (but shouldn't be required)

**Comment by sseneca** [comment]
I tried changing `transparent` but the issue persisted

**Comment by matze** [comment]
Same here. No matter if `transparent` is set to `true` or `false` or not set, see the same behaviour.

**Comment by matze** [comment]
The suggested keys did not work either. However it does indeed work with neovim master, I was running 0.7 before. Not sure, if this is ideal though.

**Comment by rebelot** [comment]
> Not sure, if this is ideal though.

It is most likely not, but I believe this issue should pertain to bufferline more than kanagawa.

What happens if you redefine `Normal` with vim syntax right after kanagawa setup?

```lua
local colors = require("kanagawa.colors").setup()
require'kanagawa'.setup({...})
vim.cmd('colorscheme kanagawa')
vim.cmd('hi Normal guifg='..colors.fg..' guibg='..colors.bg)
```

**Comment by rebelot** [comment]
Please checkout latest commit and see if it's still an issue.

**Comment by matze** [comment]
Fixed it for me. Thanks!

**Comment by sseneca** [comment]
Also appears to be fixed for me, thank you!

**Comment by matze** [comment]
Urgh, the latest bufferline changes have re-introduced this issue :see_no_evil:

**Comment by rebelot** [comment]
That's weird, but it seems to be working fine on nightly. Could you open an issue on bufferline? I seriously don't know how it expects hlgroups to be defined
