### ISSUE TITLE
Background issue on fidget.nvim

### ISSUE THREAD

**Issue by dtomvan** [rebelot/kanagawa.nvim#54]
Recently I've started using j-hui/fidget.nvim. The background of the UI is always pitch black, not the blueey color that is the default background.

Example:
![image](https://user-images.githubusercontent.com/51440893/175325733-1f17427d-538e-4aff-a941-94994515cf6e.png)

**Comment by rebelot** [comment]
that is the correct color for `NormalFloat`, I think this is intended by the plugin author

**Comment by dtomvan** [comment]
Ah, It's my bad: I have a line in my init.lua:
```lua
vim.cmd 'hi Normal guibg=NONE ctermbg=NONE'
```

This gives my terminal the ability to decide the background color. It works well, as I use the same colorscheme for my terminal, so I see a slightly transparent version of the background color.
