### ISSUE TITLE
More color options between `bg_dark` and `bg`

### ISSUE THREAD

**Issue by sanka047** [rebelot/kanagawa.nvim#55]
At the moment, the difference between `NormalFloat` and `Normal` is very large. Is there any intention of adding more color options between the two (in the same way we have a lighter gradient of background colors)? Personally, I'd like to see a couple more colors that aren't as high contrast when creating floats (having more options will let users customize certain floats to have different highlights).

**Comment by rebelot** [comment]
Yes, I am thinking about a rewrite of UI colors shades to better support various elements with minimal overlapping, like:
- `Folded`
- `CursorLine` / `CursorColumn`
- `NormalFloat`
- `WinSeparator` / `VertSplit`
- `StatusLine[NC]`
- `NormalNC`
- `WinBar[NC]`
- `Pmenu`, `PmenuSel`, `PmenuThumb` and `PmenuSbar` (<-- these will be a good template for UI windows, as you pretty much have all window elements there: main text, dimmed text, main background, selection background, scrollbar fg/bg)

This will also ease the writing of a light theme.

I am also thinking about including a minimal HSL module to adjust colors on the fly
