### ISSUE TITLE
Problem with scrollbar transparency

### ISSUE THREAD

**Issue by neriusmika** [rebelot/kanagawa.nvim#68]
After commit a8df1c0, scrollbar from dstein64/nvim-scrollview plugin lost transparency.
![image](https://user-images.githubusercontent.com/23192030/185579418-263875e0-70c3-43aa-ac11-9b72ecd368eb.png)
With other color themes, there is no such problem.
![image](https://user-images.githubusercontent.com/23192030/185579933-21936d2b-cc36-429b-a14e-26865ccd3062.png)

**Comment by rebelot** [comment]
I skimmed through scrollview plugin and the highlight color for the scroll bar (`ScrollView` hl) should default to `Visual`. Make sure kanagawa is loaded _before_ every other UI plugins.

No recent commits whatsoever should mess with that. Please confirm that the problem is the recent commit by rolling back to it and update the screenshot using the same colorscheme...

**Comment by neriusmika** [comment]
I've tried everything I can. I disabled other plugins, changed the loading order, nothing worked. Transparency works fine with all other color themes. Only in Kanagawa, it's opaque. After investigating, I found the highlight which was causing the problem:
```NormalNC = config.dimInactive and { fg = colors.fg_dark, bg = colors.bg_dim } or { link = "Normal" },```
After disabling this line or enabling dimInactive, everything works as expected.

**Comment by neriusmika** [comment]
I solved the problem in my configuration with override `NormalNC = { bg = "NONE" }`. So far, I have not noticed any side effects.

**Comment by neriusmika** [comment]
By the way, I just checked the same configuration on my work machine, where neovim nightly was not updated recently and there is no such issue. The problem seems to be with a recent neovim commit. Maybe neovim's #19871 is related to this.

**Comment by rebelot** [comment]
I do not understand why NormalNC, did you change the default highlight group for the plugin? Afaik it should link to visual.

**Comment by neriusmika** [comment]
No, I didn't.

**Comment by neriusmika** [comment]
I think it's a bug introduced with neovim pull request #13457. Other themes were not affected, so I thought that's your plugin was the cause.
