### ISSUE TITLE
Vimdoc color issues when conceal is off

### ISSUE THREAD

**Issue by ckipp01** [rebelot/kanagawa.nvim#7]
Hello! Thank you for this incredible colorscheme. I'm absolutely loving it so far. I noticed something today which is maybe a bit niche and I've honestly never really thought about the highlight groups that are at play here, but in my own plugin I am often editing my `*.txt` help file. When ` conceallevel` is set to 0 things like `*` or `|` are pretty impossible to see in various places. I'll give you a couple examples:

### `*` in headings

![2021-12-24 21 52 45](https://user-images.githubusercontent.com/13974112/147371964-2f7b1b61-eff6-4b6a-b6fa-256309e7427a.gif)

Notice it's not visible at all unless you are on top of it

### Usages of `|`

![2021-12-24 21 54 08](https://user-images.githubusercontent.com/13974112/147371992-e87615e7-bc36-4c1c-acda-d7b4737e6344.gif)

Notice here that they are really hard to see by are actually around every command in that list. You also notice in that shot that the "`" is incredible hard to see as well

Let me know if there is anything else I can provide for this. Again, wonderful colorscheme. I'm really really enjoying it so far. Here is a little beauty shot:

<img width="1786" alt="Screenshot 2021-12-23 at 21 52 09" src="https://user-images.githubusercontent.com/13974112/147372019-5950a287-0fbc-4881-b66a-30cb344c7bd4.png">

**Comment by rebelot** [comment]
Fixed in 10bccb5e8e8530725c8059df2e6852fb01842d1c

Thank you for your detailed description and the cool beauty shot!
