### ISSUE TITLE
Missing WinBar highlight group

### ISSUE THREAD

**Issue by fragov** [rebelot/kanagawa.nvim#70]
May you add WinBar highlight groups?

My suggestion:
```
hi WinBar cterm=NONE gui=NONE guibg=#16161d
hi WinBarNC guifg=#727169 guibg=#16161d
```

**Comment by rebelot** [comment]
WinBar highlights were added :)

**Comment by fragov** [comment]
There is still no way to differentiate between active and inactive WinBar:
![Capto_Capture 2022-08-24_10-09-28_PM](https://user-images.githubusercontent.com/5961188/186503153-b48f5b6c-3234-4164-b775-67476be853e0.png)
With colors, which I had suggested, it looks like this:
![Capto_Capture 2022-08-24_10-10-16_PM](https://user-images.githubusercontent.com/5961188/186503273-25b509ff-5c6a-423f-98f2-ecf60c189b1d.png)

**Comment by rebelot** [comment]
I will update the colors to differentiate active/inactive winbar, although I don't want it to have a background color.

**Comment by fragov** [comment]
I styled it the same as status line. I removed status lines, and when you use horizontal splits, there is no visual separation between them.

**Comment by rebelot** [comment]
I'll think about it. Config overrides are here for this reason: anyone can customize the theme to their best liking :)
