### ISSUE TITLE
Python Treesitter doesn't highlight properly

### ISSUE THREAD

**Issue by DMunkei** [rebelot/kanagawa.nvim#74]
So I've been mainly trying out the dark theme with python.  And the syntax highlighting doesn't seem to be working properly. 
I'm on Neovim nightly and have the latest Treesitter installed.
[![image](https://user-images.githubusercontent.com/17084284/190476639-6d451d96-7ad6-4eea-b04b-0f95b94c4347.png)](url)

Here is an example of the same snipper inside of `Pycharm` as a comparison.
[![image](https://user-images.githubusercontent.com/17084284/190476575-98d278e1-0b0f-4be8-8a95-eeee58575f1d.png)](url) 

So I was wondering about if I have something wrong, or how I might add the missing colours? Are there specific colours that should be applied?

**Comment by rebelot** [comment]
Is treesitter highlighting enabled? Do you have the python parser installed?

**Comment by DMunkei** [comment]
I've got TS enabled. But might be that I have done something wrong. Do you have an example how it should look?

**Comment by rebelot** [comment]
Look at the readme screenshots. Python highlighting is pretty rich.

**Comment by DMunkei** [comment]
You were right, sorry! I noticed that I had installed Treesitter but didn't call it during start up.
[
![image](https://user-images.githubusercontent.com/17084284/190585464-f90fec6f-82a8-40a6-a148-9eea2f321f94.png)
](URL)
This definitely looks much better, haha! I'll close this as it's not an issue at all.
