### ISSUE TITLE
W18: Invalid character in group name error in older Neovim version

### ISSUE THREAD

**Issue by dchang** [rebelot/kanagawa.nvim#77]
Hey, thanks for a great colorscheme. Recently updated my plugins and started getting _W18: Invalid character in group name_ errors. I'm on Neovim 0.7.2 and found this is due the capture group names in 631e0aa where `@` was added in a later version. My `:h group-name`:

![image](https://user-images.githubusercontent.com/50090/196783709-73a3a991-80e3-49b6-9154-da6f9fb2fe96.png)

Not sure if you want to update any documentation, maybe tag the previous working commit fc2e308, or have another solution so just reporting it for now. Using `{ 'rebelot/kanagawa.nvim', commit = 'fc2e308' }` in packer config works for me.

**Comment by rebelot** [comment]
Thanks for the suggestion, I've opened and pinned #79, hope that helps!
