### ISSUE TITLE
kanagawa.nvim is not working properly for Rust code after last update

### ISSUE THREAD

**Issue by LaBatata101** [rebelot/kanagawa.nvim#78]
Here is kanagawa.nvim at commit `fc2e30820c73b0cf56bb0fb9e4a83dd8b90f9bf4` with nvim-treesitter at commit `4cccb6f494eb255b32a290d37c35ca12584c74d0` (before the removal of obsolete `TS*` highlight groups)
![Screenshot from 2022-10-19 18-05-31](https://user-images.githubusercontent.com/20308796/196804459-fdbac500-6c7b-40f9-8cf7-88888f3b7d26.png)

Here is a screenshot after the update, `self` and `TODO:` has no color . kanagawa.nvim at commit `a6f8ea10900e8d891f9c93e0ed258f118010fb24` and nvim-treesitter at commit commit `b9bcbf8d73b5a6c3e04922936b5fc500b436d4f5`
![Screenshot from 2022-10-19 18-06-10](https://user-images.githubusercontent.com/20308796/196804471-f0225360-f773-476a-a51f-d3da9a5dbcaa.png)

I'm not sure if this is a problem with the kanagawa or with treesitter.

**Comment by rebelot** [comment]
I am pretty sure this is due to rust-tools implementation of LSP semantic highlighting. They probably link tokens to tree sitter highlights, which are now missing.

**Comment by LaBatata101** [comment]
The problem appears to be because I was using an old build of version 0.8, after I update neovim the issue was fixed.
