### ISSUE TITLE
html tagged literals not getting highlighted correctly

### ISSUE THREAD

**Issue by abenz1267** [rebelot/kanagawa.nvim#80]
![Screenshot_20221020_214053](https://user-images.githubusercontent.com/7055955/197042415-1666a41b-b246-4354-a9b3-8826cd7f0b44.png)

Hi,

i just noticed that tagged html literals don't get highlighted correctly anymore.

Regards

**Comment by vitaliydolbilov** [comment]
Looks like lower case html elements aren't being highlighted properly - upper cased components are
<img width="157" alt="Screen Shot 2022-10-21 at 11 23 16 AM" src="https://user-images.githubusercontent.com/103660206/197253712-49f8c4ca-c540-43e9-b081-99f372d53120.png">

**Comment by abenz1267** [comment]
yeah, i can confirm that jsx highlighting is broken as well.
