### ISSUE TITLE
Error in nvim-dap-ui

### ISSUE THREAD

**Issue by neriusmika** [rebelot/kanagawa.nvim#84]
An error occurs in the nvim-dap-ui plugin when running `PackerSync`. 
`packer.nvim: Error running config for nvim-dap-ui: ...packer/start/nvim-dap-ui/lua/dapui/config/highlights.lua:74: bad argument #2 to 'format' (number expected, got nil)`. 
The problem disappears after commenting these highlights:
```lua
-- DapUIStop = { link = "Error" }, --guifg=#F70067"
-- DapUIUnavailable = { link = "Comment" }, --guifg=#424242"
```

**Comment by rebelot** [comment]
weird, I couldn't rerproduce the error but highlights were not right, should be fixed now https://github.com/rebelot/kanagawa.nvim/commit/fb733c1043a462155b52cd97efd920f1dd72d33a

**Comment by neriusmika** [comment]
After the update, the error is gone. Thank you.
