### ISSUE TITLE
no pointer or prompt for selection in telescope floating window

### ISSUE THREAD

**Issue by kraxli** [rebelot/kanagawa.nvim#85]
Thanks first for this beautiful and fast color scheme! 

Searching for files by Telescope,  I miss is a pointer or prompt for the file  selected in the Telescope floating window

![kanagawa_no_prompt](https://user-images.githubusercontent.com/8371948/204154403-3bbc976e-0243-43c9-88a5-b6e8c94ca120.png)

In contrast, in other color schemes, I see which file is selected (here by a brighter background, others have a mark on the left side, e.g. `>`)

![nightfox_telescope_promp](https://user-images.githubusercontent.com/8371948/204154490-d7b6bc1a-a9ce-4927-ac51-d70b7eee1a46.png)

Is this an option, configuration or not yet supported?

**Comment by rebelot** [comment]
this is not how default telescope should look like, it seems that you (or some of your plugins) redefining telescope highlight groups.

**Comment by kraxli** [comment]
Thanks and sorry for filing this so. I will investigate
