### ISSUE TITLE
New Neovim highlight groups

### ISSUE THREAD

**Issue by Lamarcke** [rebelot/kanagawa.nvim#86]
A new update with support for semantic tokens has been pushed into the [master ](https://github.com/neovim/neovim/pull/21100)branch of Neovim.
It also features [new highlight groups](https://github.com/neovim/neovim/blob/master/src/nvim/highlight_group.c#L267), i tought it was ok to let you know.

**Comment by Lamarcke** [comment]
By the way, great work with the theme! I use it everywhere.

**Comment by rebelot** [comment]
I think I'll leave it like that for the moment, this is still a new feature and it's being worked on. I'll consider tweaking it once its stable enough (i.e. modifiers support)

p.s. thanx :)

**Comment by kting28** [comment]
@Lamarcke  you can link them yourself if you can't wait for the official support:
For example I really want the C-preprocessor skipped code to be shown as comments, so adding `lsp.type.comment` link to `@comment` is enough for this limited use case. I tested it with the 0.9 nightly.
```lua
function M.setup(colors, config)
    config = config or require("kanagawa").config
    local theme = colors.theme
    return {
            -- ["@lsp.type.class"] = { link = "Structure" },
            -- ["@lsp.type.decorator"] = { link = "Function" },
            -- ["@lsp.type.enum"] = { link = "Structure" },
            -- ["@lsp.type.enumMember"] = { link = "Constant" },
            -- ["@lsp.type.function"] = { link = "Function" },
            -- ["@lsp.type.interface"] = { link = "Structure" },
            -- ["@lsp.type.macro"] = { link = "Macro" },
            ["@lsp.type.method"] = { link = "@method" }, -- Function
            ["@lsp.type.comment"] = { link = "@comment" }, -- Comment
            ["@lsp.type.namespace"] = { link = "@namespace" }, -- Structure
            ["@lsp.type.parameter"] = { link = "@parameter" }, -- Identifier

```

**Comment by rebelot** [comment]
They are supported after the "overhaul"

**Comment by kting28** [comment]
> They are supported after the "overhaul"

Awesome! Thanks for the great work
