### ISSUE TITLE
W18: Invalid character in group name error

### ISSUE THREAD

**Issue by notwidow** [rebelot/kanagawa.nvim#87]
Hi, I am using this colorscheme. I yesterday installed Kali Linux and it has neovim version 0.7.2 r-3 but this colorscheme gives that error in kali. but it does not give that error to me in Alpine, Arch and Artix which uses neovim version 0.8.1 .. in the readme i just check here it says nvim version 0.6 or greater. so please help.

**Comment by ddigeronimo** [comment]
@notwidow Looks like this is the problem discussed in #79. I had this issue and upgrading to version >= 0.8 like they advise fixed it for me.
