### ISSUE TITLE
Folded Lines look off

### ISSUE THREAD

**Issue by chrisgrieser** [rebelot/kanagawa.nvim#89]
here is how folded lines look in kanagawa
<img width="681" alt="Pasted image 2022-12-28 10 04 07" src="https://user-images.githubusercontent.com/73286100/209787250-b2ee1032-7195-4a32-8859-fb001884c815.png">

and here how it looks in other themes (e.g., nightfox here)
<img width="540" alt="Pasted image 2022-12-28 10 04 28" src="https://user-images.githubusercontent.com/73286100/209787303-d2b5e823-c278-4c8e-b971-8de13d470e26.png">

**Comment by rebelot** [comment]
What plugin are you using? UFO?

**Comment by chrisgrieser** [comment]
yes, I'm using UFO

**Comment by rebelot** [comment]
> yes, I'm using UFO

I need to know what is the name of the faulty highlight group and what it defaults to.

**Comment by chrisgrieser** [comment]
it *should* be `UfoFoldedBg`, but I tried changing that group, but it does not seem to be it, so I am actually not totally sure which highlight group exactly is causing this 🤔

**Comment by phdhary** [comment]
it's `MoreMsg` just like in [customize fold text](https://github.com/kevinhwang91/nvim-ufo#customize-fold-text) section

**Comment by chrisgrieser** [comment]
yes, can confirm `vim.cmd.highlight({"def link MoreMsg Folded", bang = false})` seems to fixes it
