### ISSUE TITLE
Unreadable text in `Neogit` diff

### ISSUE THREAD

**Issue by kuntau** [rebelot/kanagawa.nvim#9]
![Screen Shot 2021-12-26 at 09 53 15](https://user-images.githubusercontent.com/327489/147396895-d141edc6-b20c-47b6-b0de-bbe4ce55f677.png)

As you can see the old text is unreadable.. red on red. I just load default, no config

**Comment by rebelot** [comment]
it should be fixed now in fd0acdb6295d17bfa7eb339c65517ec43657189a. Please let me know if that's ok for you.

**Comment by kuntau** [comment]
Thank you. Perfect!
