### ISSUE TITLE
Ruby symbols and variables have same colors (with tree-sitter)

### ISSUE THREAD

**Issue by otavioschwanck** [rebelot/kanagawa.nvim#91]
<img width="160" alt="image" src="https://user-images.githubusercontent.com/9551316/210149318-f935b021-e156-46ec-b2b6-f420db17dd1c.png">

Example with other theme:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/9551316/210149324-063a6e4b-a62e-4a37-a4c4-fab4a7da6307.png">

Kanagawa for helix:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/9551316/210149489-ce5fc01d-be38-4891-9b77-39d3004563f5.png">

**Comment by rebelot** [comment]
If you are running on latest release, could you please show the output of `:Inspect` command on the badly highlighted keyword?
